### ISSUE TITLE
Accommodation products price not being used

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#101]
Accomm products currently do not have price added to cart. 

Product settings:
![screen shot 2017-04-12 at 7 50 36 am](https://cloud.githubusercontent.com/assets/4634416/24956254/ddbd0c56-1f54-11e7-982a-6eac471697a0.png)

Product with date selected and booking in cart:
![screen shot 2017-04-12 at 7 52 10 am](https://cloud.githubusercontent.com/assets/4634416/24956291/f87ff9fe-1f54-11e7-93e7-c9496b702351.png)

#### Affected ticket(s)

n/a

#### What I expected

For prices to carry through to the front end. 

#### What happened instead

Products are free.

#### Steps to reproduce the issue

1. Create new Accomm product
1. Add price under Rates tab
1. Save product and view on front end
1. Add day or days to cart
1. Price will be 0

@roykho 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment]
Reproduced on Pressable:
WooCommerce 3.0.1
Bookings 1.10.0
Accommodations 1.0.8

**Comment by bor0** [comment]
@jessepearson can you please re-verify this after #103? Thanks!

**Comment by jessepearson** [comment]
@bor0 Tested and it works in current master, thanks! 👍
