### ISSUE TITLE
Duration rules not being used

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#102]
Accomm products have a min/max duration set for the number of nights a customer can book. These rules are not being used. 

Rules:
![](http://cld.wthms.co/kUPS+)
Image Link: http://cld.wthms.co/kUPS

Product:
![](http://cld.wthms.co/Fvq9+)
Image Link: http://cld.wthms.co/Fvq9

#### What I expected

Rules in settings to be used.

#### What happened instead

Rules are not being used.

#### Steps to reproduce the issue

1. Create an Accomm product with calendar always available
1. Try to select 3+ days (which is 2+ nights)
1. Receive notice

@roykho 

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment]
Reproduced on Pressable:
WooCommerce 3.0.1
Bookings 1.10.0
Accommodations 1.0.8

Minimum duration set to 1
Maximum duration = 7

Trying to select 3 nights leaves an error message `The maximum duration is 1`

**Comment by jessepearson** [comment]
May be related to #100

**Comment by bor0** [comment]
@jessepearson can you please re-verify this after #103? Thanks!

**Comment by jessepearson** [comment]
@bor0 This is corrected in the current master, thank you 👍
