### ISSUE TITLE
Resource costs not calculated

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#107]
When testing #87 I found that resource costs were not being added to the booking cost. 

#### Affected ticket(s)

n/a

#### What I expected

Resource costs to be included and to be added to the cart

#### What happened instead

They were not

#### Steps to reproduce the issue

1. Create a new Accomm product with a Standard Room Rate
1. Add a Resource to the product, either Auto or Customer assigned
1. Add either or both a Base or Block cost to the Resource
1. View product and add to cart
1. Only Standard Room Rate will be applied

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by djcowan** [comment]
Resource costs are not being added to product specific Rate adjustments (Cost for this time period)

**Comment by bor0** [comment]
@djcowan if you have found an issue with resource costs please file a separate ticket along with instructions to reproduce. Thanks!
