### ISSUE TITLE
Today showing green and available when actually booked

### ISSUE THREAD

**Issue by linkhousemedia** [woocommerce/woocommerce-accommodation-bookings#110]
#### Affected ticket(s)

566417-zd-woothemes

#### What I expected

"Today" to show as unavailable because there is a booking.

#### What happened instead

Shows green and available. When I click on it, it says "0 days available" (which it should since it's booked)

#### Steps to reproduce the issue

Added by @jessepearson
1. Create an Accomm product, make sure to set the calendar always be viewed
1. View product and add a booking for "today" and a future date
1. View booking in admin under *in-cart* bookings
1. Change start date to "yesterday" or some other past date and change status to **Paid**
1. View product again, and you will see "today" is still available to be clicked on

On this specific instance TODAY, go to https://www.harmonyoutdoorinn.com/product/the-birches/ and notice that April 21st is showing available. It is actually booked per the screenshots attached. I suppose one could test this locally.  I'm on build pr108 of Accommodation Bookings.

**Here's my woothemes ticket with screenshots:**
_WooCommerce Accommodation bookings (dev build woocommerce-accommodation-bookings_pr108) has an issue where today is showing green and available for a product that is not available. The days surrounding today are not available. Screenshots attached._

<img src="http://i.imgur.com/9mL09Zb.png">
<img src="http://i.imgur.com/5DCgqMG.png">
<img src="http://i.imgur.com/OH1FexH.png">

Post: https://www.harmonyoutdoorinn.com/product/the-birches/

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
@linkhousemedia Great report! I just confirmed this and sent it over to see if we can get a fix in the next release.

**Comment by linkhousemedia** [comment]
Fabulous. Cheers!

**Comment by linkhousemedia** [comment]
@bor0 Please tag me when there is a build that I can test. Thank you.

**Comment by jessepearson** [comment]
@linkhousemedia Master has this fix merged with it now if you'd like to check it out. 👍

**Comment by linkhousemedia** [comment]
@bor0 and @jessepearson I don't believe this was actually fully fixed.  Here's what I did just now to test:

1. Create a booking manually for one night starting today (no order)
2. No other bookings in the vicinity of this one
3. Go back to product and both today and tomorrow show as partially booked but of course I cannot make a booking using those two dates as check-in and check-out. 

*Desired Result:*
Today should show as *fully booked* if there is an existing, on-going booking OR if today is the first night of the booking, as nobody can select it as a check-in or check-out date.  

Create booking
http://i.imgur.com/793R0dA.png

View Booking (today should show as fully booked)
http://i.imgur.com/hLIyJbi.png

Select dates
http://i.imgur.com/HM2kSX1.png

**Comment by jessepearson** [comment]
@linkhousemedia So if *today* only has **check out** available, it should show **fully** booked instead of **partially** booked, correct?

Just created #112 to get this fixed ;)

**Comment by linkhousemedia** [comment]
Yes that's correct. Thanks... I should have created a new one and linked to this. My bad.
