### ISSUE TITLE
Change calendar to default to Calendar always visible

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#113]
![](http://cld.wthms.co/RvSo+)
Image Link: http://cld.wthms.co/RvSo

Change the default setting for the calendar to *Calendar always visible* for Accomm products. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
Moved to the ideas board
