### ISSUE TITLE
Display price is showing incorrectly

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#114]
Price shows incorrect due to it is being divided by the min duration. The code for this is currently [here](https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/master/includes/class-wc-product-accommodation-booking.php#L154-L156)

#### Affected ticket(s)

[forum thread](https://wordpress.org/support/topic/change-the-from-100-per-night-display-value/)

#### What I expected

Price shown to be correct. 

#### What happened instead

Price shown is incorrect

#### Steps to reproduce the issue

1. Create new Accomm product
1. Set the **Min nights available** to 2+
1. Set the **Standard room rate** to 100+
1. View the product and the price shown will be the **Standard room rate** divided by the **Min nights available**, which is incorrect

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by Elan42** [comment]
Why this is so unstable ?
Please solve this problem :(

**Comment by jessepearson** [comment]
@Elan42 This bug is not a stability issue, it's just a cosmetic problem. The functionality of how a booking works, and the pricing applied are still correct.

**Comment by Elan42** [comment]
Cosmetic issue?? 
We are online,  in production,  with a website renting apartments with a wrong (cosmetic)  price. 

Customers of our customer,  compliain about that and want discounts in the prices. 
We are losing thousands of $ every day.

**Comment by jessepearson** [comment]
@Elan42 Yes, the correct price is still charged, so it is a cosmetic/display issue. 

If this is costing you money, please download the version from PR #116 , test on a staging site to make sure the prices are displayed correctly, and then deploy to your production site once confirmed.
