### ISSUE TITLE
[Product Vendors compatibility] Commission field is missing

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#115]
#### Affected ticket(s)

568876-zd-woothemes

#### What I expected

To set vendor commission on my Accommodations product

#### What happened instead

Even though bookable products have a commission field, accommodations ones do not:

![Screenshot](http://cld.wthms.co/j1QuY+)
Screenshot: http://cld.wthms.co/j1QuY

I can only set commission globally for the whole vendor. When I do that, I can see it's calculated correctly on accommodations orders:

![Screenshot](http://cld.wthms.co/QWmll+)
Screenshot: http://cld.wthms.co/QWmll

#### Steps to reproduce the issue

Set up a Vendor Accommodations product and try to set commision on it.

Reproduced with:
WooCommerce 3.0.5
Accommodations Bookings 1.0.9
Bookings 1.10.1
Product Vendors 2.0.29

As bookable products already have this field and globally set commissions are working fine, this shouldn't be a big problem to implement.

CC @jessepearson 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
Changed this from a bug to an enhancement per the notes here: https://github.com/woocommerce/woocommerce-product-vendors/pull/261

Accommodations does not properly calculate commissions at this time when used with Product Vendors.

**Comment by laurendavissmith** [comment]
Moved to the ideas board
