### ISSUE TITLE
Tax fields missing

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-accommodation-bookings#118]
#### Affected ticket(s)

568578-zd-woothemes

#### What I expected

To see the Tax fields in the General tab, like for Bookable products.

#### What happened instead

No Tax fields.

![](http://cld.wthms.co/hrI4v+)
**Image Link**: http://cld.wthms.co/hrI4v+

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
Fixed in #117
