### ISSUE TITLE
Availability rules being ignored

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#120]
Currently availability rules are being ignored. 

#### Affected ticket(s)

568578-zd-woothemes

#### What I expected

For availability to match the rules set. 

#### What happened instead

I can only make one booking, even though 5 should be available.

#### Steps to reproduce the issue

1. Create new Accomm product
1. Set calendar to display by default
1. Set availability to 5
1. Save
1. View product and select a few days in a week
1. Days between check in and check out will show fully booked ❌ 

Open for screenshots:
<details>

![](http://cld.wthms.co/pHPhx+)
Image Link: http://cld.wthms.co/pHPhx

![](http://cld.wthms.co/wlyKN+)
Image Link: http://cld.wthms.co/wlyKN

![](http://cld.wthms.co/UZUGf+)
Image Link: http://cld.wthms.co/UZUGf

</details>

<br />
<br />
@mattyza 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by kristinaplauche** [comment]
I confirmed. 
![screenshot](http://cld.wthms.co/4c5C2+)
Image link: http://cld.wthms.co/4c5C2

**Comment by jessepearson** [comment]
I believe this issue is here:
https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/1.0.9/includes/class-wc-accommodation-booking-date-picker.php#L101-L108
