### ISSUE TITLE
_wc_booking_cost being used for Accommodation products

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#124]
`_wc_booking_cost` is the **Base cost** for bookable products, however, this field is not used for Accommodations. If a user were to start off with a bookable product, then switch to an accommodation product, this field remains populated and is used in calculations. 

#### Affected ticket(s)

568578-zd-woothemes

#### What I expected

Bookable product costs to not affect Accomm products.

#### What happened instead

...they do.

#### Steps to reproduce the issue

1. Create a Bookable product with a base cost of 5
1. After saving, switch it to an Accomm product
1. Set the Standard room rate to 5, save it
1. View product, select a day/night
1. Cost will be 10 instead of 5 ❌ 

I think the easiest solution here would be to just add that field to the Accomm settings. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by WPprodigy** [comment]
This is a lot more of an issue than it seems I believe. When I create a new test site and create a simple accommodation product like this: http://cld.wthms.co/WIGJOt, it doesn't work and shows as $0: http://cld.wthms.co/4dOZF

**Comment by MindyPostoff** [comment]
Another report of this in an atomic site on WordPress.com: 787750-zen

**Comment by ValeDeOro** [comment]
The customer booked a WooCierge session to get the bug sorted. Is there an ETA on this, so I can tell him whether to wait or to look for an alternative solution?

**Comment by ValeDeOro** [comment]
Changing this to critical, because without being able to charge for the accommodation, the plugin is essentially broken (from the customer point of view).

**Comment by jessepearson** [comment]
@mattyza Something must have changed in the most recent version of Bookings that is causing this to be more of a problem. If I recall correctly, this was previously only an issue if a customer created a Bookable product, entered a cost, then switched the product to being an Accommodation product. Now it seems this happens for all new Accommodations products.

**Comment by jessepearson** [comment]
@laurendavissmith @bor0 
Just got an update on this in 787750-zen , and it's fixed, but not at the same time. If existing Accomm products have the 0 (or other number) in place, then the incorrect cost is still used until the Accomm product is saved again. The problem here is that this began in an update and customers may not know that the incorrect prices are being used until several orders have gone through. Not sure if it's worth an update script, though.

**Comment by mattyza** [comment]
Re-opening this, to ensure this doesn't get lost.

**Comment by dwainm** [comment]
I have a WIP branch on this locally.

**Comment by dwainm** [comment]
Spent some time looking into this. 

Adding a workaround for this has caused many other data issues which I don't think is worth the headache.

The update script is not worth it as I see it as a niche case and we have a workaround.

The only viable option here is to advise users to resave the product.

CC @mattyza

**Comment by mattyza** [comment]
Thanks @dwainm. @jessepearson, is there somewhere we can note this for Happiness' reference?

**Comment by ValeDeOro** [comment]
We could add this to the FAQs on both the Booking documentation as well as on the dotorg repository docs (where the accom plugin lives). Something like: 

**Q: Why do my Accommodation Products show higher prices than I defined in the dashboard?**
A: If your accommodation product was created before [date?], it is possible that a recent update changed the existing pricing calculation. The best way to make sure that your prices are correct is to save your existing accommodation product and then test again, whether the prices are correct."

@jessepearson Does this reflect more or less the situation? What do we need to add there?

**Comment by jessepearson** [comment]
@dwainm @mattyza @ValeDeOro Sorry for the late reply, a bit behind on emails. 

Advising them in the FAQ to do this would work, I just don't know how many customers aren't noticing if the correct amount is being charged to them or not. I guess that would be a *shame on them* for not noticing that the right amount is being charged?

If we're okay with that, then the FAQ is fine. I wouldn't include a date, I'd just start it off at "It is possible..."

**Comment by mattyza** [comment]
Thanks @jessepearson @ValeDeOro. Re-opening so we can get the docs updated.

Would you mind helping with wording this, @ValeDeOro ?

cc @dwainm

**Comment by laurendavissmith** [comment]
@mattyza @jessepearson @ValeDeOro How does this wording sound? Minor tweaks based off the discussion. Also who can update the docs for us?

**Q: Why do my Accommodation Products show higher prices than I defined in the dashboard?**
A: Due to the caching that we utilize it is possible that a recent update changed the existing pricing calculation. The quickest way to make sure that your prices are correct is to save your existing accommodation product again. The save will update the cache and the price on your site will now reflect what you have defined in your dashboard."

**Comment by ValeDeOro** [comment]
I can update the FAQs in our docs. Not sure who'd do the FAQs in the repo, though. Who manages those? 

Q: Why do my Accommodation Products show higher prices than I defined in the dashboard?
A: If the prices shown on the product do not match the prices defined in the dashboard, the caching mechanism used for pricing calculation is most likely still using old information (e.g. when you updated the prices, or when changing a Bookable product to an Accommodation product). The quickest way to make sure that your prices are correct is to save your existing accommodation product again. The save will update the cache and the price on your site will now reflect what you have defined in your dashboard.

^^ Does this sound good?

**Comment by ValeDeOro** [comment]
https://docs.woocommerce.com/document/woocommerce-accommodation-bookings/

**Comment by ValeDeOro** [comment]
Looks like in order to get it into the repository one of you lovely people needs to add this information to the readme.txt file of the plugin.
