### ISSUE TITLE
Accommodation products enforce using range selection in calendar

### ISSUE THREAD

**Issue by bulgaru** [woocommerce/woocommerce-accommodation-bookings#126]
#### What I expected

When configuring the product, to have the option to enable the calendar and disable range selection (i.e. i select only the start date for the booking and indicate the number of nights in the input box).

#### What happened instead

There is no option to disable range selection. 

#### Steps to reproduce the issue

1. Create bookable product first, with enabled calendar and disabled range selection
2. Change product type to accommodation.

#### Further details

We've been able to achieve the desired functionality by editing the file: [/includes/class-wc-product-accommodation-booking.php](https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/master/includes/class-wc-product-accommodation-booking.php) and changing the function: 
`	public function is_range_picker_enabled() {
		return false;
	}`

Yet we're not happy with editing the core and we were wondering if it's possible to add this to the settings or maybe have a way to hook into the function.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
@bulgaru I created a filter to be able to change this setting in PR #128. Can you test out the branch there and let me know how the filter works for you?
