### ISSUE TITLE
Fully booked days not showing correctly when persons are used

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#129]
If persons are used and counted as bookings, days that are fully booked do not show fully booked.

#### Affected ticket(s)

Found when testing #127.

#### Steps to reproduce the issue

1. Create Accomm product with below settings
1. View product
1. Select date range
1. Increase person count to 15 (to max out availability)
1. Add to cart
1. Calendar will show days as partially booked, not fully booked ❌ 

![](http://cld.wthms.co/pyG1CB+)
Image Link: http://cld.wthms.co/pyG1CB

![](http://cld.wthms.co/6TUuZG+)
Image Link: http://cld.wthms.co/6TUuZG

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by budzanowski** [comment]
This waits for https://github.com/woocommerce/woocommerce-bookings/pull/1242 and will need to be retested or worked on after the 1242 lands.

**Comment by budzanowski** [comment]
With 1.10.4 problem still exists.
