### ISSUE TITLE
Start and End Date Not Populated on Bookings

### ISSUE THREAD

**Issue by silicondales** [woocommerce/woocommerce-accommodation-bookings#130]
#### What I expected

Installed woocommerce (3.0.8), woocommerce bookings (1.10.3) and woocommerce accommodation bookings (1.0.9) in plain old twenty seventeen theme.

A simple accommodation product is made with a zero fee to test. 

After booking, the start and end date should display here:

![image](https://user-images.githubusercontent.com/17259256/27395475-d373abe4-56a7-11e7-86ec-b2350fb2c983.png)

#### What happened instead

The accommodation bookings don't add the start and end date to the booking:

![image](https://user-images.githubusercontent.com/17259256/27395547-0fc2e86c-56a8-11e7-986c-75a8bd754ac8.png)

#### Steps to reproduce the issue

Pasting the system status here:

`
### WordPress Environment ###

Home URL: https://staging.cbcaravanpark.co.uk
Site URL: https://staging.cbcaravanpark.co.uk
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.6
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: Ou8I7k835_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Accommodation Bookings: by WooCommerce – 1.0.9
WooCommerce Bookings: by Automattic – 1.10.3
WooCommerce: by Automattic – 3.0.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by silicondales** [comment]
So this is a staging site of the client install - I'm going to test in an fresh copy to sanity check if there's something weird going on in there.

**Comment by silicondales** [comment]
Urgh its client side...

![image](https://user-images.githubusercontent.com/17259256/27396077-e4e95016-56a9-11e7-949d-6e16614a246c.png)

Sorry for flagging this.

**Comment by silicondales** [comment]
Ah I found it. Its so simple - somehow the checkin and checkout time was removed from settings on one of the upgrades (must have been WC update of Oct 20126 as that is all that updated when it "stopped working"), strangely enough this data was populating in the order side as it should, but was not stored in WC settings. Going in there it was blanko, and re-populating this info causes everything else to work as expected... its one perhaps to flag up in docs somewhere, but otherwise, just a very quirky upgrade bug (from upgrade to WC 2.6.x at that!).

**Comment by fabrikgrafik** [comment]
Hi,

I'm experiencing this exact issue on my live site at the moment. Is there something we can do to fix this? A solution would help me out so hard!! I've been going nuts to figure out what happens. I have to email a customer to ask them what dates they booked now ... which is pretty embarrassing.

**What happens:**
1) Clients makes booking and chooses start & end date
2) Client goes to cart, everything still lookes fine: ([Screenshot](https://cl.ly/0T422u1q1p1d))
3) Client advances to checkout, everything still ok:  ([Screenshot](https://cl.ly/460y1l1j212h))
4) Client confirms payment and advances to "order-received" BROKEN, dates are not showing: ([Screenshot](https://cl.ly/1M16272i0z0j))
5) When I check the admin start and end date of the booking is not present (also on booking detail page in admin): ([Screenshot](https://cl.ly/3L1f3w0n0s2g))

**Extra notes:**
•From step 4, my database (sql) shows no start or end time which normally is expected:  ([Screenshot](https://cl.ly/2x1A2D2j1W3O))
•No start and end dates are showing in mails to customer or admin

Thanks!
Nicolas
