### ISSUE TITLE
Woocommerce booking

### ISSUE THREAD

**Issue by Rj2580** [woocommerce/woocommerce-accommodation-bookings#131]
hello, I have a car business where the availability is custom. I have a car type 1, with maximum 5 availability, but it varies monthly, so I have used the resources to override the availability function. 
![1](https://user-images.githubusercontent.com/29622208/27422267-22e46198-574b-11e7-9971-4bb23965640d.jpg)
![2](https://user-images.githubusercontent.com/29622208/27422268-231ba202-574b-11e7-9014-640755647bd9.jpg)
![3](https://user-images.githubusercontent.com/29622208/27422274-23295708-574b-11e7-9d2c-543ff0854760.jpg)

From month June to September availability by resources is set 1, but it shows the user the product is partially booked after making 1 booking,
![4](https://user-images.githubusercontent.com/29622208/27422290-31ab0dda-574b-11e7-9e64-176fa6bfb789.jpg)
 On the same time, it won't allow the booking when the block is selected by the customer. 
![5](https://user-images.githubusercontent.com/29622208/27422344-6a36603c-574b-11e7-9288-4944e45e1498.jpg)
I think it's quite confusing for the customer during booking as he is unaware which block is actually partially available and which one is fully booked.

**Comment by jessepearson** [comment]
@Rj2580 Can you create a ticket through your http://WooCommerce.com account, then let us know your ticket number? This repo is for bugs with Accommodations and isn't for support of Bookings.

**Comment by jessepearson** [comment]
*Reopening, just in case you cannot add the ticket number in a closed issue.*

**Comment by bor0** [comment]
I wasn't able to reproduce this, but it's possible I'm missing some configuration for the Booking product. @Rj2580 can you please check if it's reproducible in 1.10.4? Should potentially be fixed by bookings/1242.

**Comment by Rj2580** [comment]
Yes its solved, thank you for your efforts.
