### ISSUE TITLE
Fallback to default checkin/checkout time values

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#133]
#### Affected ticket(s)

593753-zd-woothemes

#### What I expected

To check booking dates of a booking for an accommodation product.

#### What happened instead

The booking didn't have any start or end date set at all:

![Screenshot](http://cld.wthms.co/WoFHD+)
Screenshot: http://cld.wthms.co/WoFHD

When I opened booking details, start and end time were at 1970 Jan 1st:

![Screenshot](http://cld.wthms.co/Zd8DX+)
Screenshot: http://cld.wthms.co/Zd8DX

This turned out to be due to the lack of check in / checkout times set in Products > Accommodations settings:

![Screenshot](http://cld.wthms.co/a2b4hs+)
Screenshot: http://cld.wthms.co/a2b4hs

As soon as I've set these, I got the bookings working back correctly.

Can we have a fallback to default values here if nothing is set?

#### Steps to reproduce the issue

1. Reset checkin / checkout times (there's no warning about this!)
2. Purchase any accommodations product
3. Observe booking start and end time, both on frontend and the backend

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
@madeincosmos I'm fine with having a default fallback value, but what should this value be?

**Comment by madeincosmos** [comment]
@bor0 that's a great question! How about 12:00 checkout & 14:00 checkin? That's most hotels I think :)
