### ISSUE TITLE
Unable to save person types.

### ISSUE THREAD

**Issue by rodrio** [woocommerce/woocommerce-accommodation-bookings#140]
#### What I expected

When configuring a product, I select "Has Persons" checkbox and "Activate Types of Persons" under Persons tab. I add a new person type, configure it and save the product. I expect the product to keep that person type so it will be shown in the front end for the customer to select number of persons of that type.

#### What happened instead

Instead, after saving the product, the person type I just created is simply gone. It's like I never created it. In the frontend, no person selection field appears. When user selects a date, it returns an error similar to "Persons needed. Choose a person number." because the system understands that I marked Activate Person Types but created no person types.

#### Steps to reproduce the issue

I believe I just described this above.

**Comment by jessepearson** [comment]
@rodrio I just tried this out with the latest versions of Bookings and Accommodations and was not able to reproduce the error. Would you be able to confirm the versions of Bookings and Accommodations you are using?

**Comment by rodrio** [comment]
Hi @jessepearson I actually have Accomodations (1.1.0) disabled and I'm using only Bookings (1.10.7)

It's important to mention:
- We have latest version of Kriesi's Enfold theme (4.1.2) and woocommerce products are using AVIA Page Builder
- We have Woocommerce Easy Booking plugin v2.1.4 (by @_Ashanna - herownsweetcode.com) which is still active and being used in other products. I tried deactivating but doesn't change anything
- We have WPML multilingual and primary language is Portuguese (PT-BR)
- We have W3 Total Cache up and running
- IMPORTANT: During tests, eventually a recently created person type became a product of its own, being listed in my products as if it was one. I had to manually trash then exclude them and I felt like somehow it detached from the woocommerce product it should be attached to.

**Comment by jessepearson** [comment]
@rodrio Would you be able to create a staging copy of the site, maybe using [WP Staging](https://wordpress.org/plugins/wp-staging/), and then deactivate everything but WooCommerce, Bookings and Accommodations and see if it still a problem?

If it is, please create a ticket under your WooCommerce.com account and let me know the ticket here so I can follow up.

**Comment by rodrio** [comment]
@jessepearson I can do that, but first I tried a few further tests and came up with the following:

Steps to reproduce:
1) Create new (blank) product
2) Choose (Enfold's) AVIA Page Builder editor instead of default editor
3) Insert Product Purchase Button (Woocommerce integration)
4) Go to pricing section and select Bookable Product
5) Mark VIRTUAL and mark HAS PERSONS
6) In the persons tab, configure minimum and maximum number of persons
7) Set the base cost, mark multiply costs per person number and mark to activate person types
8) Create first person type, set name, set description, set base cost and leave block price as zero
9) Set this type's minimum and maximum and SAVE

If I stop here, the newly created person type is shown in the frontend for the user to select. But if I move on two things go wrong...

1) If I create another person type and configure it just as the first one (with new name, description and base cost) and SAVE or...

2) If I go to costs and set the base cost to zero and SAVE...

...then for both options above all person types are gone! Nothing shows up in the frontend, except the calendar. Whenever you select a date on the calendar, then it comes with the message "Persons needed. Choose a person number.".

**Comment by jessepearson** [comment]
@rodrio This sounds like it may be a conflict with the theme. If you use a default theme like 2017, or the default editor, does the problem still occur. 

Again, I encourage you to create a ticket through your WooCommerce.com account for troubleshooting/support purposes.

**Comment by rodrio** [comment]
Hey Jesse,

Thanks for your time and patience. I will reach them. Have a great day!

**Comment by jessepearson** [comment]
@rodrio If you let me know the ticket number, I can make sure it's followed up on :)
