### ISSUE TITLE
Woocommerce single product really slow when this product has long booking duration

### ISSUE THREAD

**Issue by enguerranws** [woocommerce/woocommerce-accommodation-bookings#142]
#### What happened

Setting a long duration in a booking for a bookable product doesn't affect single product template rendering. After some debugging, I can see that it's coming from the rendering the datepicker which has to check if each day is free, booked or partially booked. from the beginning of the first booking, to the last day of the last booking.

#### Steps to reproduce the issue

Make a new booking, set it over the product booking max date. 
E.g : your product booking max date is 6 months in the future, so set a booking manually to this product to more than 6 months. The rendering the datepicker will make WP check for days that won't be displayed.

#### What was expected

Rendering the datepicker shouldn't check for each days since the first booking starting day to the last booking ending day: it should check for each days from today to the product booking max date, so it won't check days that won't be displayed.

**Comment by jessepearson** [comment]
@enguerranws You're correct about this, I found where the problem is, and it's within Bookings itself and not Accommodations. I am going to create a bug in that repo about it.

**Comment by jessepearson** [comment]
Actually, the problem is [on this line](https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/master/includes/class-wc-accommodation-booking-date-picker.php#L141), `get_all_existing_bookings` should be used instead of `get_bookings_for_objects`.

**Comment by enguerranws** [comment]
Will `get_all_existing_bookings` will get the relevant booked days? (by relevant, I mean: between today and the end of the displayed calendar)

**Comment by jessepearson** [comment]
`get_all_existing_bookings` gets the min/max times from the product settings and then limits the query of existing bookings to between those dates. I've just created a pull request if you'd like to test it out, you can download the edited version here: 
https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/fix/issue-142
