### ISSUE TITLE
Add rate option to discounted Standard Room Rate for specific number of nights booked.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-accommodation-bookings#145]
Similarly to how the **Block count** cost option for Bookable products, allow a store owner to reduce the rate for an Accommodation product based on duration of stay.

Currently, users can only override the cost ( _Standard Room Rate_ ) for a range of dates rather than reduce the cost based on duration of stay.

See: [Change Price of Booking Based on Duration Stay](https://docs.woocommerce.com/document/change-price-booking-based-on-duration-stay/)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by WPprodigy** [comment]
Had a request for this today. It does make a lot of sense that people would need to offer discounts to appeal to those staying for a longer period of time.

**Comment by DustinHartzler** [comment]
I had this request today too, via a WooCierge chat 959551-zen.

Seems like this is pretty standard in the hotel industry to charge $100 for a night, but if you reserve two nights, then the per night cost goes down to $95 (or whatever) per night.

**Comment by melindahelt** [comment]
Had another request for this in live chat today

**Comment by laurendavissmith** [comment]
Moved to the ideas board
