### ISSUE TITLE
Be able to view remaining bookable blocks for day-based blocks

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-accommodation-bookings#146]
A customer in chat today asked to be able to view his remaining bookable blocks, but he was using day-based blocks (instead of time-based blocks). It would be great to be able to view the blocks remaining with day-based blocks on hover on the calendar.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
Moved to: https://github.com/woocommerce/woocommerce-bookings/issues/1420
