### ISSUE TITLE
Can't block certain dates for checkin only

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#147]
#### Affected ticket(s)

726671-zen

#### What I expected

To disable checkin on October 31st (but still let customers check out on that day)

#### What happened instead

I've added the following availability rules:

![Screenshot](http://cld.wthms.co/DZqL1O+)
Screenshot: http://cld.wthms.co/DZqL1O

All dates with a 'No' can't be selected in the calendar, even as a checkout date:

![Screenshot](http://cld.wthms.co/V89C7w+)
Screenshot: http://cld.wthms.co/V89C7w

Global availability rules taking checkin and checkout hours also don't help.

#### Steps to reproduce the issue

1. Create an accommodation product and add a few rules excluding certain dates (i.e. as above)
2. Open the product on the frontend and observe this day can't be used for checkout
3. Delete all rules on the product and replace them with a Global Availability rule that has a date range with time:

![Screenshot](http://cld.wthms.co/cQqlse+)
Screenshot: http://cld.wthms.co/cQqlse

4. Observe this time you're both able to checkin and checkout on that day, despite it should be blocked for checkin.

![Screenshot](http://cld.wthms.co/y3MloS+)
Screenshot: http://cld.wthms.co/y3MloS

Reproduced on Pressable, Bookings 1.10.8 & Accommodations 1.1.0

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by iMazed** [comment]
Howdy folks! The user in ticket 726671-zd-woothemes is still waiting for an answer on this one. Can we get an update on it, please? :) thank you!

**Comment by jessepearson** [comment]
I believe this is a limitation of the jQuery datepicker itself, it only turns full days on or off, and it isn't aware if a day should be only selectable in certain instances. 

The team would need to create logic within the JS that uses the datepicker to determine if the date is available for check out, but not for check in. As @madeincosmos mentioned, it's a very similar instance in https://github.com/woocommerce/woocommerce-bookings/issues/1491

**Comment by jobthomas** [comment]
Just to add to this 1999836-zen

I think it fits in here as well - not just should you be able to checkout on a day that's already booked for checkin, if you minimum have to book for 2 consecutive days, you shouldn't be able to be allowed to choose a start day that conflicts with this rule. 

For example:

![1999836](1999836+)
Link to image here: 1999836.

In this case:

* 15 shouldn't be allowed to be chosen as a start date
* 14 should be allowed to be chosen as a start date, but then with 16 as an end-date

**Comment by budzanowski** [comment]
@jobthomas that is absolutely correct, you should not be able to choose start dates that will not allow selection of any end date. That being said this is a different Issue :) Would you mind opening a new Issue?

**Comment by budzanowski** [comment]
@madeincosmos @jessepearson if you would find some time could you check this with:
 - https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/202 
and
 -  https://github.com/woocommerce/woocommerce-bookings/pull/1781

PRs for both accommodation and booking plugins are required to make this work.

**Comment by AashikP** [comment]
Also reported in 2104666-zen

@budzanowski I tried installing them both for testing purpose. While I can activate the fix for accommodations, trying to activate bookings gets me this error. Am I doing something wrong here 🤔?

> Plugin could not be activated because it triggered a fatal error.

```
( ! ) Warning: include(/app/public/wp-content/plugins/woocommerce-bookings/vendor/prospress/action-scheduler/action-scheduler.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php on line 54
--
1 | 0.0000 | 407640 | {main}( ) | .../plugins.php:0
2 | 0.1602 | 6682168 | plugin_sandbox_scrape( ) | .../plugins.php:175
3 | 0.1603 | 6683520 | include( '/app/public/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php' ) | .../plugin.php:2141
```

**Comment by budzanowski** [comment]
@AashikP that is correct. The plugin in the repository is in the raw state. 
Before being able to use it you need to run `npm run build` inside the plugins directory.

**Comment by c-shultz** [comment]
After some team discussion, I'm changing this to an enhancement and closing it out. This request should be moved to the ideas board for future consideration.

We understand why some stores would expect checkout times to work this way, but there are differing needs for different store owners, so building out this functionality will require a bigger effort with design involvement to make this easy to use and to properly account for all major use cases.

Slack convo for further context: https://a8c.slack.com/archives/CAKN301C3/p1563547720335600
