### ISSUE TITLE
When i add a product to the cart, the whole product disappears for all users

### ISSUE THREAD

**Issue by nrodriguez02** [woocommerce/woocommerce-accommodation-bookings#151]
776840

 I expected the product keep been visible with the appoinments days mark like happends with woocommerce booking instead

The whole product disappears for all the users and also dissapear the wordpress admin top bar in that page until the product was removed from the cart

set some product on type accommodation booking and add to cart
i try with other theme like Storefront in a clean instalation and the same thing happend

![step1](https://user-images.githubusercontent.com/22350864/32468485-a02b3d2e-c335-11e7-93c5-f5b9ee5ae2e0.jpg)
![step2](https://user-images.githubusercontent.com/22350864/32468486-a04ca978-c335-11e7-9937-218fafad586f.jpg)
![step3](https://user-images.githubusercontent.com/22350864/32468487-a06ede4e-c335-11e7-95f0-4d6fef199641.jpg)
![step4](https://user-images.githubusercontent.com/22350864/32468488-a0d2475e-c335-11e7-8771-8bbbf070ea4f.jpg)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mattyza** [comment]
@nrodriguez02 - Hi there. It sounds like perhaps your availability settings for this product are set that only one is available/in stock?

I'm curious about the admin bar disappearing. That could be caching, or a styling conflict with your theme or another plugin.

**Comment by nrodriguez02** [comment]
Hi mattyza, i'm trying everithing 
I already try on a clean installation on my localhost, with another theme "Storefront" and using only the 3 plugins needed Woocommerce 3.2.3, Woocommerce Bookings 1.10.1 and Woocommerce Accommodations 1.1.0 and happend the same issue... 
Also i did some test and that issue only happends with Woo Accomodations, when i put the product type on Booking and add the product to the cart everithing goes fine... Do u have another idea of what it's going on??

This is exactly the error report, maybe you cand find out what is wrong...

2017-11-06T15:03:22+00:00 CRITICAL Uncaught Error: Call to undefined function wc_bookings_get_time_slots() in /home/lesliepelaez/public_html/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking-date-picker.php:170
Stack trace:
#0 /home/lesliepelaez/public_html/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking-date-picker.php(117): WC_Accommodation_Booking_Date_Picker->get_product_resource_available_blocks_on_time(Object(WC_Product_Accommodation_Booking), 0, 1511013600)
#1 /home/lesliepelaez/public_html/wp-includes/class-wp-hook.php(298): WC_Accommodation_Booking_Date_Picker->add_partially_booked_dates(Array, Object(WC_Product_Accommodation_Booking))
#2 /home/lesliepelaez/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#3 /home/lesliepelaez/public_html/wp-content/plugins/woocommerce-bookings/includes/class-wc-bookings-controller.php(272): apply_filters('woocommerce_boo...', Array, Object(WC_Product_Accommodation_Booking))
#4 /home/

Thanks a lot

**Comment by nrodriguez02** [comment]
I already fixed by let this line

/**
	 * Get amount of available product resoureces on a specific timestamp
	 * *@param $product
	 * *@param $resource
	 * *@param $date
	 */
	private function get_product_resource_available_blocks_on_time( $product, $resource, $time ) {
		$blocks = $product->get_blocks_in_range_for_day( $time, $time, $resource, array() );
		**$available_blocks = wc_bookings_get_time_slots( $product, $blocks, array(), 0, $time, $time );
		return ! empty( $available_blocks[ $time ] ) ? $available_blocks[ $time ][ 'available'] : 0;**
	}

equal 0;

and everithing seems right but i guess that line was for something so i hope you can help me find the real problem and fix it..
Thanks

**Comment by nrodriguez02** [comment]
Solved!! Was a problem with the version of woo bookings, i update the plugin and the problem get fixed
