### ISSUE TITLE
Corrupted check-in dates in DB

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-accommodation-bookings#153]
Found this on a customer site, 

![error](http://cld.wthms.co/utFLdx+)

which caused "Sorry, the selected block is not available" or "Sorry, bookings cannot start on this day." errors for every date depending on the restrictions setup. Essentially it causes the `_start_date` to be empty in the data because of this line: https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/15f58dbb2d6de2392d8d85f1203a39e26270232c/includes/class-wc-accommodation-booking-date-picker.php#L36

I'm not 100% sure how this happened (the PM should not be there) and I couldn't replicate, but fairly postive the user didn't manually edit the DB. So some conditions aligned to cause this. Some sanity checks would be nice to prevent such an edge case issue in the future.

**Comment by WPprodigy** [comment]
Update: Oh, it's here: https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/7cd81bcf8e9cb36a6fbf76706d1d1d58c1b920b0/includes/admin/class-wc-accommodation-booking-admin-product-settings.php#L40

Saving the fields removes the AM/PM and solves the error. The default data is wrong. Also, if we are going to have default data it should show up in the admin as well in the fields for checkin/checkout rather than them starting blank.

**Comment by bor0** [comment]
@WPprodigy can you confirm the proposed PR fixes the issue? Thanks!

**Comment by WPprodigy** [comment]
I couldn't replicate how these defaults actually ended up being used, but I'm gonna assume that fixes it.

One other thing though - it would be nice if the defaults showed up in the settings, at the moment the times are just empty even though apparently defaults are set.

**Comment by bor0** [comment]
@WPprodigy can you tell me how to reproduce that?

They seem to show up properly on my side. Initially they're showing 14:00 and 12:00. I set them to 15:00 and 11:00 and then they show as 15:00 and 11:00 on reload. Also in the database:
```
mysql> select * from wp_options order by option_id desc limit 2;
+-----------+----------------------------------------------+--------------+----------+
| option_id | option_name                                  | option_value | autoload |
+-----------+----------------------------------------------+--------------+----------+
|      7781 | woocommerce_accommodation_bookings_check_out | 23:00        | yes      |
|      7780 | woocommerce_accommodation_bookings_check_in  | 15:00        | yes      |
+-----------+----------------------------------------------+--------------+----------+
2 rows in set (0.00 sec)

```

**Comment by WPprodigy** [comment]
Scratch that, it's working now 👍
