### ISSUE TITLE
Calendar Shows Incorrect Image on Checkout Date

### ISSUE THREAD

**Issue by keninbassart** [woocommerce/woocommerce-accommodation-bookings#154]
#### Affected ticket(s)

775262-zen

#### What I expected

When booking an accommodations product that already has an existing reservation the calendar should show the first half of the first day of the reservation greyed out, then the full days greyed out, then the checkout date should be greyed out on the _first half_ of the day. 

#### What happened instead

In this case the checkout day has the incorrect portion of the day greyed out which is a bit visually confusing and also inconsistent:

![calendar](http://cld.wthms.co/73V1FK+)

The actual functionality is correct here in terms of allowing the booking to be made, it's just the visual element that should be adjusted here. 

#### Steps to reproduce the issue

WooCommerce Bookings & Accomodations
Set up a product with a check-in/out time
Book a series of dates
Return to the same product and attempt to book another booking for the end date of the previous booking.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by danjjohnson** [comment]
I looked into a temporary CSS fix, but it seems there is no difference in CSS classes between a partially booked date on check-in date or check-out date, so there is nothing available to target for this change, it will require some more extensive changes.

**Comment by danjjohnson** [comment]
@mattyza I'm guessing this won't be a high priority. Is it worth keeping the ticket on hold or should we tell the customer it will likely be a while before it's addressed?

**Comment by mattyza** [comment]
@danjjohnson - I'd suggest informing the customer that this will be addressed in one of the next two minor versions of Bookings (1.11, or 1.12) and in the first half of 2018.

**Comment by csscallum** [comment]
This is definitely classed as a temporary CSS hack but I have implemented the following code on a site I'm currently developing: 

`.fully_booked + .partial_booked a:after {
    right: auto;
    left: 0;
    transform: rotate(180deg);
}`

The above CSS simply flips the red triangle and positions it left of the date box.

**Comment by madeincosmos** [comment]
@LaurenaRehbein moving over here from https://github.com/woocommerce/woocommerce-bookings/issues/1520, as your suggestion applies best to accommodations products rather than general bookings.
