### ISSUE TITLE
Confusing Special Rates

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-accommodation-bookings#156]
The "range of weeks" option here is pretty confusing: http://cld.wthms.co/yDW6sg. The customer at first thought it was dynamic, meaning they could offer discounts rates for the second week the customer was booked with them. (This isn't possible, but I think it should be https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/145 :) )

Turns out, it is actually just a way to change the prices based on the 52 weeks of the year. I think we should just remove this completely though, as they could instead just enter dates in a much less confusing manner.

**Comment by laurendavissmith** [comment]
Closing for now, we'll revisit if we get more reports for it
