### ISSUE TITLE
Unclear wording of the message that shows when a day is fully booked

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#157]
#### Affected ticket(s)

804967-zen

#### What I expected

To make a booking that overlaps with fully booked days.

#### What happened instead

I got the following error message that's not super user friendly:
```
There are a maximum of 0 places remaining on 29/11/2017
```
![Screenshot](http://cld.wthms.co/HhAyZh+)
Screenshot: http://cld.wthms.co/HhAyZh

It would be much simpler to say "29/11/2017 is fully booked! Please choose different dates".
#### Steps to reproduce the issue
1. Create an Accommodations product, min stay 1 night, max 7 nights
2. Make a booking for one night, i.e. 29/30 Nov.
3. Try to make a booking for several nights that includes the one that has been booked (i.e. 28 Nov - 1 Dec).
4. Observe the error message.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
After chatting with @dkotter I'm going to close this as `wont fix` for now as that block of code really needs to be refactored before we start addressing the specifics of the wording and potentially causing more confusion
