### ISSUE TITLE
Check-in and Check-out days - add class for styling to differentiate the two

### ISSUE THREAD

**Issue by sstudebaker** [woocommerce/woocommerce-accommodation-bookings#159]
#### What I expected

The Calendar is causing a great deal of confusion as far as what dates are available for booking. Example is at http://www.galenalodge.com/product/stars-perch-yurt/ (See January). My client is getting many calls about this as people are frustrated trying to book a yurt stay.

![screen shot 2017-11-27 at 12 51 36 pm](https://user-images.githubusercontent.com/11078433/33286370-63b68e14-d372-11e7-8675-069b09a7bbd4.png)

#### What happened instead

What would be SO helpful is if a class was attached to Check-in and Check-out days to differentiate between the two (rather than just partially booked) and then calendar could be styled accordingly. For instance calendar triangles could show check-in and check-out dates as lower right triangle and upper left triangle respectively. This would go a really long way to helping people understand what is open for booking.

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
Moving to the ideas board for further evaluation
