### ISSUE TITLE
My Account > Bookings page shows only up to 5 bookings

### ISSUE THREAD

**Issue by NickKellett** [woocommerce/woocommerce-accommodation-bookings#165]
#### Affected ticket(s)

None

#### What I expected
This might be a Bookings bug, but anyway...I am using the Accommodations extension and I have created approximately 11 orders and bookings for a user account. When I login as that user and go to My Account > Orders page, I can view all my orders on the Orders page, and paginate between the Orders result set. When I go to the My Account Bookings page, I expected to see all the bookings as well.

#### What happened instead

However, when I go to the My Account > Bookings page, it only shows the latest 5 bookings. There is no button to show more than those 5.

#### Steps to reproduce the issue

1. In the Admin dashboard, create at least 6 new bookings for the same customer, each with a different order.
2. Go to the front-end and login as that user
3. Go to My Account > Orders page and verify you can see all 6 orders, and navigate to the next page if required.
4. Go to the My Account > Bookings page, and verify that you can only see 5 of the bookings, and no way to navigate to the next booking.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).
![booking bug](https://user-images.githubusercontent.com/11150209/34083198-32826d4a-e33a-11e7-8ae9-8b49088dc905.png)

**Comment by jessepearson** [comment]
@NickKellett There should be a *next* link at the bottom of the page similar to this:

![](http://cld.wthms.co/zdCpjq+)
Image Link: http://cld.wthms.co/zdCpjq

If it isn't there, it's a Bookings issue either with variables or templates. If you add another booking, just for testing sake, and it doesn't appear, please submit a support ticket.

**Comment by unlimitedit** [comment]
Same problem seen on one of my client's sites (see attached image). 'Next' button missing. Limited to 10x _Upcoming Bookings_ and 10x _Past Bookings_. Need an quick fix please.

Woocommerce 3.2.6
Woocommerce Bookings 1.10.11
WordPress 4.9.1

![woocommerce_bookings_10_visible_limit](https://user-images.githubusercontent.com/7138599/34574458-5d338de2-f16f-11e7-925c-3356689bf44c.png)

**Comment by NickKellett** [comment]
I've submitted support ticket to WooCommerce.
