### ISSUE TITLE
Option to add more than one calendar

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce-accommodation-bookings#17]
Can we make request here? I would like calendar pop up to span two month on the front end and if possible also to have separate calendar for check in and check out, not one for the both - something like this image: http://www.formisimo.com/blog/wp-content/uploads/2015/06/Bookingcom-date-picker.png

From this site all about booking forms. http://tinyurl.com/jar9rz7

**Comment by ajgw** [comment]
Well I saw this too. There I miss a label or info to customer that after clicking on date for check in, that afterthen the check out date has to be checked. Put a label on top of calendar which tells customer what kind of date is to be checked. In this case it will be more responsive to customer. Thanks.

**Comment by laurendavissmith** [comment]
Moved to the ideas board
