### ISSUE TITLE
Add Rate Range by Person Count In Accommodation Product Type

### ISSUE THREAD

**Issue by levymktg** [woocommerce/woocommerce-accommodation-bookings#171]
When creating an accommodation product that includes persons, the option of setting a rate range by persons count is not available as it is in a bookable product.

I need to set a nightly room rate where there is a base rate that is for double occupancy, but the accommodation can host up to 8 people.  For each additional person from 3 - 8, there is a $50.00 up charge.

Currently, I am able to use a bookable product to achieve this type of rate range, but I would love to be able to use the other available functionality of the accommodation booking plug in.

![screenshot 2018-02-05 11 54 35](https://user-images.githubusercontent.com/20331542/35820544-8419993c-0a6b-11e8-96b8-93b31addbc64.png)
![screenshot 2018-02-05 11 55 01](https://user-images.githubusercontent.com/20331542/35820551-879d2d76-0a6b-11e8-8bc0-be23ac32fde4.png)

**Comment by amandasjackson** [comment]
another request for this here 1029753-zen

> Apartment 2: 40 euro for 2 people per night and adding another 10 euro per night for each more person up to 4 total. 
> Example: 2 people = 40 euro, 3 people = 50 euro, 4 people = 60 euro per night. 
> High season i.e August the base 40 euro increases to 50 euro per night and the subsequent pax at 15 euro each per night. 
> So for August 4 people at 80 euro per night.

**Comment by laurendavissmith** [comment]
Moving this to the ideas board for further evaluation

**Comment by Sukalo0290** [comment]
> Moving this to the ideas board for further evaluation


Why has this been completed but never resolved? 5 years later this still doesn't have the basic range types featured in the Booking option. Block count ( price based on amount of nights ) and based on Person count should be usable for accommodation too.
