### ISSUE TITLE
Add an option to autocomplete accommodation orders

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#179]
#### Affected ticket(s)

1010518-zen

#### What I expected

To set Accommodation order status to Completed upon payment instead of Processing.

#### What happened instead

For Bookable products this is possible by making the product virtual (see: https://github.com/woocommerce/woocommerce-bookings/issues/1257 )

However, Accommodation products don't have the Virtual flag and so it's not possible to autocomplete their orders this way.

It's worth checking if bringing that flag back will default to the way Bookings handles this. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment]
CC @jessepearson @bor0

**Comment by bor0** [comment]
Hidden in 435afa62.

**Comment by bor0** [comment]
@madeincosmos can you check if #180 resolves it? Thanks!

**Comment by madeincosmos** [comment]
Thanks @bor0! I can make the product **Virtual** now, but orders don't autocomplete - this probably works only for bookable products ATM

**Comment by bor0** [comment]
Thank you @madeincosmos! I used the same approach in Bookings for `WC_Booking_Order_Manager::complete_order`. The reason it didn't work is that the code in Bookings works specifically for products of type `booking`, and we need `accommodation-booking` so I updated the PR.

**Comment by madeincosmos** [comment]
Works fine for me now ✔️

**Comment by bor0** [comment]
^ cc @laurendavissmith

**Comment by stephhjacq** [comment]
Hi @bor0 @laurendavissmith any updates on when this will be released? Thanks
