### ISSUE TITLE
No calendar and no featured image on Accommodation product

### ISSUE THREAD

**Issue by botea14** [woocommerce/woocommerce-accommodation-bookings#181]
Hi guys,

I use WooCommerce Bookings and WooCommerce Accommodation Bookings plugins.

If i set my room as Bookable product, it displays calendar and featured image and i can select period and book hotel room.

If i select my room as Accommodation product, it only displays the price and the room title.

> Accommodation prodcut
> ![accomodation](https://user-images.githubusercontent.com/37483645/37558765-caddbeae-2a21-11e8-97ec-802d54f78baa.PNG)
> 

> Bookable product
> ![bookable](https://user-images.githubusercontent.com/37483645/37558766-cb1fc470-2a21-11e8-9c8a-ec432c9c4da4.PNG)

In page code source (chrome) i can only see this text:

```
<div class="summary entry-summary">
--
  | <h1 class="product_title entry-title">Family Room Breakfast Included</h1><p class="price">From <span class="woocommerce-Price-amount amount">190,00&nbsp;<span class="woocommerce-Price-currencySymbol">lei</span></span> per night</p>
  |  
  | <noscript>Your browser must support JavaScript in order to make a booking.</noscript>
  |  
  | <form class="cart" method="post" enctype='multipart/form-data'>
  |  
  | <div id="wc-bookings-booking-form" class="wc-bookings-booking-form" style="display:none">


```

Can anyone tell me how can i fix this ? PLEASEEE!

Thanks.

**Comment by jessepearson** [comment]
@botea14 This isn't a place for support, submit a ticket here so someone can assist you:
https://woocommerce.com/my-account/tickets/

Once you've created the ticket, you can place the number back here for follow up.
