### ISSUE TITLE
Cost of automatically assigned Resource is hidden on the front end.

### ISSUE THREAD

**Issue by gspitzer** [woocommerce/woocommerce-accommodation-bookings#182]
#### What I expected

If there is an extra cost for the displayed room rate, that should be shown on the product page as well.

#### What happened instead

Room rate is $100, automatically assigned Resource cost is $50, so the total for booking 7 nights is $750. As a customer, I have no information about the additional $50.

#### Steps to reproduce the issue

- Create an Accomodation product.
- Set Room rate / Display rate $100.
- Add automatically assigned Resource with base cost $50.
- Check the product page, book the room for 7 _(or any number of)_ nights, the total will be $750; as a customer, I don't know why I should pay that "extra" $50.

![https://cloudup.com/czBEKF3bvB9](https://cloudup.com/czBEKF3bvB9+)

Image Link: https://cloudup.com/czBEKF3bvB9

It would be useful to display / see all costs of a product, so the total is not surprising. 

Marking it as a High Priority bug _(please adjust)_ - it is working, but from the customer's perspective the cost of the automatically assigned Resource can be considered as "hidden cost" which can harm a business.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
This issue comes from Bookings, and Bookings has the same behaviour with automatically selected resources. With manual selection, things are more obvious. In any case, I am closing this 2 years old issue as it doesn't seem to be that big of a deal.
