### ISSUE TITLE
Booking Duration Not shown in email

### ISSUE THREAD

**Issue by gfaulk09** [woocommerce/woocommerce-accommodation-bookings#184]
#### What I expected
I expected it to show the duration in the email just as it shows on the cart page.

<img width="398" alt="screen shot 2018-05-10 at 8 11 19 am" src="https://user-images.githubusercontent.com/39159971/39871278-df72136a-5429-11e8-8415-38aca9526166.png">

#### What happened instead
What happens instead is that the customers and the admin emails only show the time of the booking and not saying the duration.

<img width="241" alt="screen shot 2018-05-10 at 8 11 32 am" src="https://user-images.githubusercontent.com/39159971/39871283-eb370fe8-5429-11e8-8ac8-9a2136b5d949.png">

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
Moved to the ideas board
