### ISSUE TITLE
Accommodation Bookings giving false warning message 

### ISSUE THREAD

**Issue by californiakat** [woocommerce/woocommerce-accommodation-bookings#186]
Getting a warning message: "Accommodation Bookings requires Bookings plugin activated.
Plugin deactivated."

<img width="418" alt="screen shot 2018-05-25 at 13 23 43" src="https://user-images.githubusercontent.com/6988393/40542108-f7bbccda-601e-11e8-9be2-212aba28f98f.png">

There should be no warning message. Both Bookings and Accommodation Bookings are activated.

Steps:
I activated Bookings plugin
I installed and activated Accommodation Bookings.
The warning message appeared.
Under Plugins, I can see both plugins are activated.

<img width="1255" alt="screen shot 2018-05-25 at 13 24 11" src="https://user-images.githubusercontent.com/6988393/40542111-001886c0-601f-11e8-9bfd-06be6b435f9a.png">
<img width="1255" alt="screen shot 2018-05-25 at 13 23 59" src="https://user-images.githubusercontent.com/6988393/40542115-04a2ad92-601f-11e8-8254-4dc96ba90300.png">

I'm using 3.4 and Storefront as my theme, and there are no other plugins/extensions/payment gateways activated.

**Comment by jessepearson** [comment]
@californiakat It's a known issue if your plugin folder isn't named `/woocommerce-bookings/`.
