### ISSUE TITLE
End date doesn't respect the `woocommerce_bookings_mdy_format` filter

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#188]
#### Affected ticket(s)
1197301-zen

#### What I expected

To display calendar dates in the DD/MM/YYYY format, like most of the world outside of US does ;-)

There's a filter for this described in the Bookings docs:

https://docs.woocommerce.com/document/bookings-snippets/#section-8

#### What happened instead

The start date does respect the filter but the end date does not, which creates even more confusion than there was before:

![Screenshot](http://cld.wthms.co/1JNPAp+)
Screenshot: http://cld.wthms.co/1JNPAp

#### Steps to reproduce the issue
1. Add the snippet:

```
add_filter( 'woocommerce_bookings_mdy_format' , '__return_false' );
```

2. Create an accommodation product with calendar not visible by default.
3. Open the product page and observe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by TheOnlineExpress** [comment]
Any help with this would be great!

**Comment by AashikP** [comment]
@bor0 pinging you since the ticket is back on top of the queue. I'm closing the ticket for now and redirecting the user here so that they can keep track of the progress.

**Comment by AbdulSamadKt** [comment]
Can I know any solutions?

**Comment by jessepearson** [comment]
@AbdulSamadKt The issue was in Bookings itself. If you create a ticket under your WooCommerce.com account, we can send you a pre-release copy of the next Bookings release.
