### ISSUE TITLE
Restrict start days during specific date range

### ISSUE THREAD

**Issue by drinkteaeatbiscuits** [woocommerce/woocommerce-accommodation-bookings#189]
My client wants to give their customers the ability to book in week long blocks (Fri-Fri) during their High Season (July-August). But for the rest of the year, give the customer the choice of booking any range of days. Is this possible? Currently I'm only able to do one or the other. 

Restricting start days during a specific period only would be ideal.

**Comment by jessepearson** [comment]
@drinkteaeatbiscuits Unfortunately this is not the place to add ideas such as this, they are better suited for the ideas board here: http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=82014

There is a search in the lower part of the right hand column, I did not find something to the affect of what you mentioned, but feel free to search before adding your idea. 

I am going to close this issue now.
