### ISSUE TITLE
Cannot Activate Accommodation Bookings

### ISSUE THREAD

**Issue by belcherj** [woocommerce/woocommerce-accommodation-bookings#192]
#### What I expected

To be able to activate extension

#### What happened instead

I got an error that said:

```
Accommodation Bookings requires Bookings version 1.9+.

Plugin deactivated.
```

#### Steps to reproduce the issue

- Install latest WooCommerce Bookings 1.11.2
- Install latest WooCommerce Accommodation Bookings 1.1.2
- Got to WooCommerce->Settings
- Observe error at top of screen

![screen shot 2018-07-30 at 10 43 13 am](https://user-images.githubusercontent.com/6817400/43404738-356708c4-93e6-11e8-8963-0f0cb02ecbd9.png)
![screen shot 2018-07-30 at 10 43 01 am](https://user-images.githubusercontent.com/6817400/43404740-3582ef94-93e6-11e8-8e82-7615f5458034.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by belcherj** [comment]
version_compare( '1.11.2', '1.9', '>='); evaluates to true not sure why this would not work:  https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/master/includes/class-wc-accommodation-dependencies.php#L52

**Comment by roykho** [comment]
Tested this today and didn't see this issue.

**Comment by belcherj** [comment]
If you can't repo, let's close it.
