### ISSUE TITLE
Can Add coupon discount Per night per room?

### ISSUE THREAD

**Issue by no4** [woocommerce/woocommerce-accommodation-bookings#195]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
@no4 No, this is not possible. You can submit an idea for possible addition of this here:
http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=337813

Additionally, this is not a support forum, you are able to submit tickets through your WooCommerce.com account.
