### ISSUE TITLE
No Shipping? Some accommodations require shipping..

### ISSUE THREAD

**Issue by joshtipton28** [woocommerce/woocommerce-accommodation-bookings#200]
There is no option for shipping. While the vast majority of rentals don't require this (I get it), there are accommodations these days that do need this functionality.  I think that this plugin is a very useful plugin and I appreciate the work you have put into it.

I am working on a project for RV/Camper Rentals and they need to charge a shipping fee based on the distance that they have to deliver. Since the shipping panel is disabled, it makes it harder to set this up. 

#### What I expected

I think that it would make your plugin better if you let the developer decide if their accommodation needs shipping or not. Again, I understand that most don't need it.

I have found that commenting out the "is_virtual" method and conditionals as well as removing the filter to hide_shipping_tab sets up this functionality.  

Perhaps there is a reason to have this baked into the plugin and if so, I'm all ears, but if there isn't a good reason for this, could this be removed from a future release?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
Similar to #214

**Comment by bor0** [comment]
This contradicts #5 #35 but since we have a couple of tickets related to it I guess we do need virtual after all.
