### ISSUE TITLE
Multiply cost by number of nights is not working

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-accommodation-bookings#205]
When setting up a product addon with a quantity based fee and checking the option "Bookings: Multiply cost by number of nights". Even though we select multiple nights, the cost doesn't multiply.

Before the PAO 3.0 compatibility changes we used to save this in the addons filed `wc_booking_block_qty_multiplier`. But this was recently changed to `wc_accommodation_booking_block_qty_multiplier`

See: https://github.com/woocommerce/woocommerce-accommodation-bookings/commit/b4a917cc5a290134c0416e0bbf759720a08ab38a

This poses a problem because the Addons plugin doesn't take this into account. If we rename this back then it will trigger the bookings functionality and again correctly multiply the cost.

I tested reverting this on my test site and it fixes the issue.

Affected chat: 8193124-hc

**Comment by mouligreenlaw** [comment]
Another ticket 1914366-zd

**Comment by mouligreenlaw** [comment]
@mikkamp Any idea when this might be fixed please.

**Comment by mikkamp** [comment]
This has again become an issue after upgrading Bookings to 1.15.0. Although the previous PR doesn't work.

Reverting back to Bookings 1.14.5 allows a quantity based addon to be multiplied by the amount of nights again.

However this happens regardless of whether the following option is checked or not:
`Bookings: Multiply cost by number of nights`

Steps to reproduce:
- Create an accommodation product with multiple nights bookable
- Add a quantity based product addon (ex. Breakfast +10 per night)
- Enable the option "Multiply cost by number of nights" for the addon
- Add the product to the cart for multiple nights
- Observe that the addon cost does not multiply times the number of nights

- Revert back to Bookings 1.14.5
- Add the product to the cart for multiple nights
- Observe that the addon cost does multiply times the number of nights
- Turn off the option "Multiply cost by number of nights" for the addon
- Observe that the addon cost still multiplies by the number of nights

Affected ticket: 2288506-zen

**Comment by ryanr14** [comment]
Howdy! Is there an update for this here issue? :)

**Comment by ryanr14** [comment]
It me again, the ticket (2288506-zen) came back around. It appears there is a PR ready for some review? :)

**Comment by mikkamp** [comment]
This has been fixed in the following PR: https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/228
Confirmed that it's now working on my test site.

Notified the user in the ticket. Also closing this since it was released yesterday.
