### ISSUE TITLE
Remove partial booking styles

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-accommodation-bookings#208]
To coincide with Bookings core, we should remove partially booked days styling to be consistent.

**Comment by roykho** [comment]
Close via https://github.com/woocommerce/woocommerce-accommodation-bookings/commit/8c98bdb3d6bbfc3de434a91b1f3884528d811b4d

**Comment by SiR-DanieL** [comment]
Related to https://github.com/woocommerce/woocommerce-bookings/issues/2396
