### ISSUE TITLE
Cannot disable virtual flag on accommodation products

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-accommodation-bookings#214]
#### Affected ticket(s)

2015696-zen

#### What I expected

The virtual flag on the product should be an option and not required. 

#### What happened instead

The virtual flag is checked by default and cannot be disabled:

![Virtual untick](https://user-images.githubusercontent.com/17844465/57365382-3c6ee380-7185-11e9-8cd6-7fcbe5169f33.gif)

#### Steps to reproduce the issue

1. Create a new accommodations product
2. Disable the virtual flag
3. Update the product
4. Note that the virtual product flag is back in place

#### Notes

Changed the behavior in version 1.1.3:
https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/179

I'd expect this to be optional rather than a requirement.  This is a problem as not all sites want accommodations bookings to be automatically completed.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dougaitken** [comment]
2669717-zen via Live Chat

Internal Slack discussion - p1580295760020600-slack-C0D9EC4H0

**Comment by tommyshellberg** [comment]
The consensus after discussing this is that we could allow the Accommodation Booking product to be non-virtual, meaning that we revert the change made previously to force it to be virtual:

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/13aca46c17f8e101f000f12c15258f7b9b39fc07/includes/class-wc-product-accommodation-booking.php#L151

We may also want to consider removing the auto-completion of orders if they contain accommodation bookings.

**Comment by amandasjackson** [comment]
another report here 2726703-zen

**Comment by rwaynick** [comment]
Hi @tommyshellberg, is there a snippet that we can provide in the meantime that would allow it to be virtual? Asking for the ticket that @amandasjackson mentioned above.

**Comment by tommyshellberg** [comment]
@rwaynick I don't see any way to use a snippet to change this. In the code shown above we can see that `is_virtual()` is hard-coded at the moment to return `true` and isn't hooked up to a filter.

Later on, the Order Manager checks `is_virtual()` and sets the status to Completed, again, without a filter available to modify that.

https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/c68c3506e8473f2bfa1e272dbe6a162edd52015d/includes/class-wc-accommodation-booking-order-manager.php#L123

**Comment by rwaynick** [comment]
I see. Thanks for checking @tommyshellberg.

**Comment by FreshPhil** [comment]
2935710-zen as well

As a work around in the meantime, people can use Automatewoo to update the order status. Not great as it's asking them to purchase another plugin, but it's an option.

**Comment by yukikatayama** [comment]
This was reported in 22168785-hc. They were hoping to disable as client wants the order to be processing first.
