### ISSUE TITLE
Ability to select starting dates that will not allow for the corresponding minimum days

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-accommodation-bookings#218]
#### Affected ticket(s)

1999836-zen

Not just should you be able to checkout on a day that's already booked for checkin, if you minimum have to book for 2 consecutive days, you shouldn't be able to be allowed to choose a start day that conflicts with this rule. 

For example:

![https://cld.wthms.co/VT4sV6](https://cld.wthms.co/VT4sV6+)
Link to image here: https://cld.wthms.co/VT4sV6.

In this case:

* 15 shouldn't be allowed to be chosen as a start date
* 14 should be allowed to be chosen as a start date, but then with 16 as an end-date

cc @budzanowski 

Requested to move over here from https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/147#issuecomment-495581094

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by budzanowski** [comment]
Thank you!

**Comment by ravinderk** [comment]
@jobthomas I am not able to reproduce this issue. Can you confirm again or Am i missing something?


https://user-images.githubusercontent.com/1784821/203236561-6f85ebe7-b58d-4bf3-bd22-294e689c7f64.mov

**Comment by jobthomas** [comment]
Minimum 2 days:
![Screenshot 2022-11-24 at 14 32 41](https://user-images.githubusercontent.com/8783673/203785659-414ce72d-8713-4d9f-9abe-545e9e7690cd.jpeg)

Booking confirmed from 2 to 4 Dec:
![Screenshot 2022-11-24 at 14 34 13](https://user-images.githubusercontent.com/8783673/203785909-699cb584-532f-4e77-9f1b-7ecb4b8b63a9.png)

I would expect from now on that: 

* I would not be able to select 2 December, because 2 December is part of this booking night. However, you'll see below that this is not greyed out
* I would not be able to select 1 December as start date, because there's no option for a 2 day long booking as available. 
* It seems that the issue of not being able to select 4 Dec as starting day is fixed

![Screenshot 2022-11-24 at 14 37 40](https://user-images.githubusercontent.com/8783673/203786435-9c04892b-4cfe-415a-911a-a0020d8795e0.png)

**Comment by ravinderk** [comment]
@jobthomas  1st and 2nd is selectable because customer can select 30th as start date and 2nd as end date (partially booked). On 2nd, customer will checkout (same as check-in time for other booking) which means room will be available for night. For this reason, these dates are available.

As per my understanding customer should able to book start date of other booking as end date, but i cann't 🤔 

cc: @jeffpaul @dkotter @faisal-alvi do you have any thoughts?

**Comment by dkotter** [comment]
> As per my understanding customer should able to book start date of other booking as end date, but i can't

I believe this is correct, you should be able to have overlap on end dates / start dates. For instance, if someone is checking out of a hotel on one day, someone else should be able to check-in on that same day. If that's not working, seems like we need to figure that out

**Comment by jobthomas** [comment]
> 1st and 2nd is selectable because customer can select 30th as start date and 2nd as end date (partially booked). On 2nd, customer will checkout (same as check-in time for other booking) which means room will be available for night. For this reason, these dates are available.

So it should be greyed out, as the 1st and the 2nd can't be used as a start date. Once the start date is selected, the end date should be available as the 1st and the 2nd.

**Comment by ravinderk** [comment]
> > 1st and 2nd is selectable because customer can select 30th as start date and 2nd as end date (partially booked). On 2nd, customer will checkout (same as check-in time for other booking) which means room will be available for night. For this reason, these dates are available.
> 
> So it should be greyed out, as the 1st and the 2nd can't be used as a start date. Once the start date is selected, the end date should be available as the 1st and the 2nd.

@jobthomas I suggest not graying out 1st and 2nd dates because customers will book only available dates. Customers will skip gray-out dates because he is not aware of the logic of the start and end date, which means profit loss to the merchant.

**Comment by jobthomas** [comment]
I'm not sure what the best solution then is. The red and struck through means that the date is not available. Is there another format we can use to flag that a date is not available as the start date, but definitely available as a night?

**Comment by jeffpaul** [comment]
@faisal-alvi I believe you may have worked on a similar situation for Bookings, mind reviewing this here and commenting with your thoughts/recommendation?

**Comment by faisal-alvi** [comment]
Yes, it's the same issue that we are trying to fix with PR #303. That PR introduces separate availability for check-in and check-out days.

![acom-201-1](https://user-images.githubusercontent.com/25176325/181000818-0322bcdd-b0db-4239-a0f1-9682d602e10e.gif)
[image link](https://www.screencast.com/t/Xl5oWSnklvx)

However, the plugin updates the availability regardless of the minimum allowed nights. The availability calculations do not include these parameters.

**Comment by jeffpaul** [comment]
@faisal-alvi what do you think is the best approach to accommodating minimum days calculations in the booking process?

**Comment by faisal-alvi** [comment]
@jeffpaul the booking process does respect the minimum day's calculations already! but when it comes to showing the days as green, it does not include the minimum day's parameter and shows the day as green even if there are not enough corresponding days available. But when the user clicks those "fake" green days, the plugin does not allow the booking and shows a message, this way the plugin respects the minimum day's calculations but it does not show green days according to that rule.

**Approach:** We will have to look into the codebase and modify the current logic to include the minimum day's parameter, but I think that fix will be made in the bookings plugin, not the accommodation plugin. @ravinderk, any thoughts?

**Comment by ravinderk** [comment]
> @jeffpaul the booking process does respect the minimum day's calculations already! but when it comes to showing the days as green, it does not include the minimum day's parameter and shows the day as green even if there are not enough corresponding days available. But when the user clicks those "fake" green days, the plugin does not allow the booking and shows a message, this way the plugin respects the minimum day's calculations but it does not show green days according to that rule.
> 
> **Approach:** We will have to look into the codebase and modify the current logic to include the minimum day's parameter, but I think that fix will be made in the bookings plugin, not the accommodation plugin. @ravinderk, any thoughts?

I confirm that this issue fixes with https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303 (if I am not missing any user case.). Let us add logic to add-on as much if possible (added comment on https://github.com/woocommerce/woocommerce-bookings/pull/3378). It will be maintainable in future
