### ISSUE TITLE
Resource Label Not Translateable

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-accommodation-bookings#221]
#### Affected ticket(s)
2109372-zen

#### What I expected
To be able to translate my resource labels.

#### What happened instead
This issue: https://github.com/woocommerce/woocommerce-bookings/issues/2191 is the blocker, but since accom adds the night duration unit, I just wanted to open this so it doesn't get forgotten about when the other issue gets fixed.

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

**Comment by m155y** [comment]
Another instance of this on 2258152-zen today.  User is attempting to update the translation for the text on the "Select Options" button.

**Comment by brezocordero** [comment]
Hi @m155y 👋 

> User is attempting to update the translation for the text on the "Select Options" button.

Looking into the ZD ticket, this is a different issue for translations in Bookings Availability.
The string "Select Options" is inside of the .pot file and is waiting for a public facing doc.
Is that correct?

If I missed something, let me know!

**Comment by m155y** [comment]
Hi @brezocordero - yes, I believe you are correct. 😄
