### ISSUE TITLE
Half booked day displays wrong

### ISSUE THREAD

**Issue by FelixAnstdt** [woocommerce/woocommerce-accommodation-bookings#231]
#In itself the plugin works fine (see first picture), but I noticed a problem (see second picture)
The problem only occurs when the last day of a booking is the first day of a new calendar column. In this case, the triangle that shows the last day as half booked is displayed upside down. You can still select the last day as the start day of a new booking (see figure three). Therefore the function behind it is correct.  Only the display is wrong. 
<img width="1440" alt="Bildschirmfoto 2019-11-21 um 10 21 57" src="https://user-images.githubusercontent.com/50164417/69324979-ba8a6780-0c49-11ea-9b10-e86a2e612dd5.png">

<img width="1440" alt="Bildschirmfoto 2019-11-21 um 10 22 05" src="https://user-images.githubusercontent.com/50164417/69325014-c544fc80-0c49-11ea-92d9-64e150cceae2.png">

<img width="1440" alt="Bildschirmfoto 2019-11-21 um 10 29 52" src="https://user-images.githubusercontent.com/50164417/69325101-e4438e80-0c49-11ea-9e73-96d402e19f53.png">

I have changed the CSS file of the booking calendar and the representation of the triangles in such a way: 
.wc-bookings-date-picker .ui-datepicker td.partial_booked 
a:before{display:none}

.wc-bookings-date-picker .ui-datepicker td.partial_booked a:after{
	content:"";
	position:absolute;
	right:0;
	bottom:0;
	width:0;
	height:0;
	border-bottom:2.9em solid #C96259;
	border-left:4.9em solid transparent;
	z-index:-10;
	opacity:.95
     }

.wc-bookings-date-picker .ui-datepicker td.fully_booked + td.partial_booked.partial_booked a:after {
	border-bottom: none;
         border-left: none;
         border-top: 2.9em solid #C96259;
         border-right: 4.9em solid transparent;
         left: 0;
         top: 0;
    }

**Comment by dexit** [comment]
I've been working the same solution, I hope over the weekend I will write a Jquery script that adjustes this.

**Comment by FelixAnstdt** [comment]
Hey @dexit, did you find a solution?
