### ISSUE TITLE
Select start day options hidden off screen

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce-accommodation-bookings#232]
#### Affected ticket(s)

2543023-zen

#### What I expected

See the full range of days to select start day.

#### What happened instead

Only Sunday - Thursday show

![https://d.pr/i/C8PEbB](https://d.pr/i/C8PEbB+)
Full Image: https://d.pr/i/C8PEbB

These options are hidden off-screen. Gif:

![https://d.pr/i/zhU2v6](https://d.pr/i/zhU2v6+)
Full Image: https://d.pr/i/zhU2v6

#### Steps to reproduce the issue

Create an accommodation booking product
Go to Availability tab
Try to set start day as Saturday
Resize window

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
This shouldn't be an issue. I believe it was fixed some time ago and I also cannot reproduce it.
