### ISSUE TITLE
Impossible to select checkout date if that date already has a booking

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-accommodation-bookings#250]
#### Affected ticket(s)

2841822-zen
20259596-hc
3003527-zen
22191587-hc 
3100146-zen
3111881-zen
21893912-hc

#### What I expected

1. Customer 1 books Apr 15-18 - which is the nights of 15, 16, 17 Apr
2. Customer 2 wants to book Apr 12-15 - which is the nights of 12, 13, 14 Apr

#### What happened instead

Step #2 is not possible with accommodations:

![](https://d.pr/i/VbldnE+)
If the image does not load, please click this link: https://d.pr/i/VbldnE.

If I want to book, I need to select the checkin and the checkout date (checkout date = last night + 1 day), e.g. 22-25 Apr:

![](https://d.pr/v/rvp8dE+)
If the image does not load, please click this link: https://d.pr/v/rvp8dE.

In the above case, 25 Apr is no blocked out once added to the cart.

So following this principle, when I try to block out 12-15 Apr, this happens, I cannot select the 15th:

![](https://d.pr/i/DTrbrf+)
If the image does not load, please click this link: https://d.pr/i/DTrbrf.

#### Steps to reproduce the issue

1. Create an accommodations product and set basic costs
2. Book 15-17 Apr and then try to book anything that has checkout on 15 Apr - it's not possible

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jrick1229** [comment]
Another report: 20259596-hc

**Comment by treibalen** [comment]
Another report in 3003527-zen

**Comment by yukikatayama** [comment]
replicated and reported in 3062310-zen

Accommodation has 5 pm checkin, 11 am checkout with a 7 day minimum.

I have a booking confirmed already for June 27-July 4. you can see that the 4th can be selected for a start date, but if I wanted to book June 20-27th, the checkout date for the 27th is blocked:

![](https://d.pr/i/U0iXmj+)
Link to screenshot: https://d.pr/i/U0iXmj

**Comment by grizzly-bas** [comment]
Hi! What's the progress on this bug? Our clients are still having issues.

**Comment by rezwiebel** [comment]
My client too...

**Comment by tsetend** [comment]
Another report in 22191587-hc was able to replicate this problem as well. Follow-up ticket here: 3094740-zen

**Comment by rezwiebel** [comment]
Is this problem new? Cause it already worked on our website. The reason we bought the plugin was to book from for example saturdays to saturdays. The saturday has to be split in (morning leaving the booked room and afternoon available for new visitor).

**Comment by jacoswan** [comment]
Also in 3100146-zen

**Comment by ldr2273** [comment]
Another report in 3111881-zen

**Comment by damiannep** [comment]
Upset user that they need to pay for customization for a bug that in their opinion, makes our product unusable. 21893912-hc

**Comment by treibalen** [comment]
I updated the initial comment with all reported tickets/chats and bumped this bug to Critical since this is a very common scenario and it's affecting a lot of merchants.
