### ISSUE TITLE
Bookings' costs allow for bulk discounts when purchasing multiple blocks, while Accommodation's rates do not

### ISSUE THREAD

**Issue by apmwebdev** [woocommerce/woocommerce-accommodation-bookings#251]
#### Affected ticket(s)

#zen-2887710

#### Issue

With a normal bookable product, the `Costs` tab allows a store admin to select `Block count` as a range type and change the base cost and block cost based on this range. This allows for the creation of bulk discounts when customers buy a certain number of blocks at a time. 
![image](https://user-images.githubusercontent.com/30607075/79609970-400d2900-80bd-11ea-98a5-855b63651f9d.png)

With accommodation products, there is a `Rates` tab instead, which does not allow for this bulk discount functionality, as there is no `Block count` range type. 
![image](https://user-images.githubusercontent.com/30607075/79610241-ccb7e700-80bd-11ea-928e-0cc7f852c283.png)

Is there a reason this functionality was excluded from Accommodations? Could it be added in? Thanks!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mikkamp** [comment]
As for the exact history on why this is different then Bookings I'm not sure. However the cost rules have been different for a long time. The scenario where you can offer a discount based on a specific block count is not currently available.

However it is something which is requested on the ideas board:
https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34596127-add-rate-option-to-discounted-standard-room-rate-f

Closing this issue as we use the ideas board for keeping track of feature requests.
