### ISSUE TITLE
New Bookable product converted to Accommodation product doesn't show check in or out form

### ISSUE THREAD

**Issue by fylgjur** [woocommerce/woocommerce-accommodation-bookings#267]
#### Affected ticket(s)

#3362119-zen and reproduced on my test site

#### What I expected/how to reproduce

- Create new product as 'bookable' and publish
- Change product to 'accommodation' type and update
- I expect to see the check in and out options on the product

#### What happened instead

I see no check in or out options in this Accommodation product: https://catevents.mystagingwebsite.com/product/cat-flat-for-rent/

Screenshot: https://snipboard.io/hXAPe1.jpg

This only affects new products that start life as Bookable. This example is originally an Accommodation product that was once changed to Bookable then back to Accommodation, that displays the options ok: https://catevents.mystagingwebsite.com/product/cat-castle-holiday-home/

#### Impact upon users

Users who start using Accommodation for the first time will have to recreate products rather than simply switching type in order to get this to function.

#### Related issues

May be related to #224 with data retained upon product switch?

**Comment by Sidsector9** [comment]
Hi @fylgjur , I am new to this product so please pardon my ignorance.

Can you tell me what is the **Calendar display mode** option set to?

I am not sure if this is an intended behavior, but after investigating a bit, I found that the check-in/out fields are only visible if the **Calendar display mode** is set to **Display calendar on click**

<img width="814" alt="Screen Shot 2022-04-14 at 12 59 01 AM" src="https://user-images.githubusercontent.com/17757960/163255809-39bb1666-8e97-4274-ae7e-6cdc5758647c.png">

If the product starts off as a bookable product with the display mode set to **Calendar always visible**, after switching it to accommodation product, the check-in/out options won't be shown. But if you switch the display mode to **Display calendar on click**, the check-in/out fields show up.

**Comment by jeffpaul** [comment]
Closing this due to no response, but please re-open if we've misunderstood things or if additional information can be provided, thanks!
