### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-accommodation-bookings#269]
We need to ensure the extension works fine with the release of PHP 8.

For more reference materials, please check out woocommerce/woocommerce#27674

**Related pull requests:**

- [ ] https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/270 - Add a custom abs method to workaround an incompatibility of the buil-in function

Checked items are already merged.

**Comment by Sidsector9** [comment]
Just to ensure the plugin is stable on PHP 7.4 and above, I've performed the following tests in PHP 7.4 and 8.0 environments:

- No issues reported by PHPCompatibility (PHP 7.4 and above) on plugin and tests files.
- PHPUnit tests run without errors on PHP 7.4 and PHP 8.0.
- Some minor warnings by PHPCompatibility tests inside the `vendor/` folder. Nothing fatal.
- No reports in debug.log

cc: @jeffpaul

**Comment by Sidsector9** [comment]
I've performed the following tests in a PHP 8.0 environment:

- No issues reported by PHPCompatibility (PHP 7.4 and above) on plugin and tests files.
- PHPUnit tests run without errors on PHP 7.4 and PHP 8.0.
- Some minor warnings by PHPCompatibility tests inside the `vendor/` folder. Nothing fatal.
- No reports in debug.log

cc: @jeffpaul

**Comment by Sidsector9** [comment]
I've performed the following tests in a PHP 8.0 environment:

- No issues reported by PHPCompatibility (PHP 7.4 and above) on plugin and tests files.
- PHPUnit tests run without errors on PHP 7.4 and PHP 8.0.
- Some minor warnings by PHPCompatibility inside the `vendor/` folder. Nothing fatal.
- No reports in debug.log

cc: @jeffpaul
