### ISSUE TITLE
The day is green even if its fully booked!

### ISSUE THREAD

**Issue by faisal-alvi** [woocommerce/woocommerce-accommodation-bookings#298]
#### What I expected

The day should be turned red when fully booked.

#### What happened instead

The day kept green even when fully booked. Selecting it shows the error, "There are a maximum of 0 places remaining on XXXX-XX-XX"

_As seen in this image: the 28th should be turned red, but its not._
![acom-issue](https://user-images.githubusercontent.com/25176325/177539310-da506554-ae6b-43d3-9882-edd8b142dfb4.gif)

#### Steps to reproduce the issue

1. Create an accommodation product.
2. Set "Number of rooms available" to "1".
3. Book (for example) the 28th and 29th of the month.
4. (28th is partially booked, so it should still have a green color)
5. Book (for example) the 27th and 28th of the month.
6. (the rest of the 28th is now booked too, so it should turn red! BUT it's still GREEN)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ankitguptaindia** [comment]
This issue is fixed by https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303 and working as expected now.
