### ISSUE TITLE
Launch calendar / date picker when clicking in From / To fields

### ISSUE THREAD

**Issue by solaceten** [woocommerce/woocommerce-accommodation-bookings#30]
Suggestion:

On the front end product booking page, you can select not to show the calendar unless it's clicked on - but there are also the Date From / TO fields. 

In my opinion, clicking in these fields should launch the calendar / date picker as illustrated in the attached screenshot - though it should also be possible for the user to write dates in these fields also.

![calendar date picker](https://cloud.githubusercontent.com/assets/2679075/13033631/34749c78-d31e-11e5-9317-232c67f23384.png)

**Comment by robertstaddon** [comment]
@solaceten This is a good idea. If this feature were to be added to the WooCommerce Bookings plugin, it would automatically appear in this plugin. You may consider adding this as a Feature Request on the WooThemes Ideas Board: http://ideas.woothemes.com/forums/133476-woocommerce/category/82014-extension-woocommerce-bookings

Here is a similar feature request that might also do the trick, which seems to have gotten a lot of traction on the Ideas Board: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/7140911-two-calendar-date-picker-one-for-start-date-one

**Comment by laurendavissmith** [comment]
Moved to the ideas board
