### ISSUE TITLE
Test against Custom Order Table implementation

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-accommodation-bookings#306]
Describe the request
Please review the [Custom Order Table testing guide](https://developer.woocommerce.com/2022/05/16/call-for-early-testing-custom-order-table-migrations/), [upgrade guide](https://github.com/woocommerce/woocommerce/wiki/COT-Upgrade-Recipe-Book), and utilize the [latest testing ZIP](https://github.com/woocommerce/woocommerce/releases/tag/feature-custom-order-table)) to see how the WooCommerce Core COT migration impacts the Accommodation Bookings extension. If you run into questions, @alefesouza at WooCommerce will be the best person to reach out to while testing this migration on Accommodation Bookings.

If things test smoothly, please leave a comment to that extent with any details of your testing.

If you run into issues, please document those here so that we can work with @alefesouza and the https://github.com/orgs/woocommerce/teams/proton team to determine if fixes are needed in WooCommerce core, Accommodation Bookings, or both.

Testing approach:

Smoke test backend (wp-admin/management screens) interfaces to ensure they continue to work as expected.
Smoke test frontend functionality with Twenty Twenty-Two or Storefront.
By the nature of this project, think of any feature that might be related to how orders are stored in the database and prioritize testing that.

**Comment by faisal-alvi** [comment]
The [upgrade guide](https://github.com/woocommerce/woocommerce/wiki/COT-Upgrade-Recipe-Book) is followed and the plugin is tested. No issues were found related to the orders in this plugin.
Other COT-related issues (found while testing this plugin) are reported in https://github.com/woocommerce/woocommerce-bookings/issues/3392.

**Comment by faisal-alvi** [comment]
✅ This is re-tested and everything working fine when COT is enabled. A few issues seen here are already [reported](https://github.com/woocommerce/woocommerce-bookings/issues/3392) in the Bookings plugin.
cc: @dkotter @jeffpaul

**Comment by jeffpaul** [comment]
@alefesouza FYI ^

**Comment by jeffpaul** [comment]
@faisal-alvi to confirm, no issues specifically here in Bookings Availability, only issues inherited as this extends Bookings?

**Comment by faisal-alvi** [comment]
@jeffpaul yes

**Comment by jeffpaul** [comment]
@alefesouza for extensions that have no changes needed, is there any sort of messaging that should be included in the plugin readme, docs, changelog, or otherwise to note that the extension is compatible with Custom Order Tables?

**Comment by alefesouza** [comment]
@jeffpaul COT Team said we will need to declare feature compatibility, but it is still work in progress. https://github.com/woocommerce/woocommerce/issues/34419

**Comment by jeffpaul** [comment]
I've labeled this as `blocked` for now while we await the Woo core API PR to get merged in https://github.com/woocommerce/woocommerce/issues/34419

**Comment by jeffpaul** [comment]
Updating to note that the WC API is being tracked in https://github.com/woocommerce/woocommerce/pull/34727, keeping this as blocked until that is merged/ready for us to work from.

**Comment by jeffpaul** [comment]
Closing in favor of #311 which will more formally declare support for COT/HPOS.
