### ISSUE TITLE
Plugin banners

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-accommodation-bookings#31]

**Comment by gedex** [comment]
@jameskoster is this something you can help with? No rush though.

**Comment by jameskoster** [comment]
@gedex Sure, I'll add to my todos :)

**Comment by jameskoster** [comment]
How about [this](https://cloudup.com/caqD6Lj6u2O)? A street full of hotels :)

**Comment by gedex** [comment]
LGTM @jameskoster. Thanks! I'll add those.

**Comment by jeffpaul** [comment]
Closing as plugin has appropriate banners/icons
