### ISSUE TITLE
Duration unit for Accommodation Booking products should be "Nights" not "Blocks"

### ISSUE THREAD

**Issue by Brianmitchtay** [woocommerce/woocommerce-accommodation-bookings#320]
#### Affected ticket(s)

5808811-zen

#### What I expected

Given that these products are booked for a number of nights, I expected that the message about minimum duration would reference the `Duration_unit` for an accommodations product as "Nights"

#### What happened instead

Instead we get the following message "The minimum duration is 3 **blocks**"

![EDq9B1.png](https://user-images.githubusercontent.com/45057772/209418027-cca7320d-70c4-4458-a980-320614d8ed8c.png)

#### Steps to reproduce the issue

- Create an Accommodations Booking Product.
- Set the minimum duration to two or more nights, the maximum to a short range as well.
- Navigate to the front end and view your product
- Select a number of days under or over the allowed range
- Note that the message refers to the `duration_unit` as "Blocks" not nights.

The user in 5808811-zen put it this way

> If you select a start day followed be the next day appearing as two “blocks” then the calendar still insists you need to select two blocks. It should perhaps say 2 “nights. This appears as a 3 block selection.

I searched and see no user-facing way to set the `duration_unit` to `nights`, so assume this is hard-coded and must be addressed by a PR.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by rtpHarry** [comment]
I've had to tackle this for a client and used this code:

```php
/**
 * Override Bookings plugin blocks / nights
 */
function soka_override_blocks($translation, $single, $plural, $number, $domain) {
	if($plural == "blocks" && $number != 1) {
		return "nights";
	}
	if($single == "block" && $number == 1) {
		return "night";
	}
	return $translation;
}
add_filter('ngettext_woocommerce-bookings', 'soka_override_blocks', 10, 5);
```

**Comment by jeffpaul** [comment]
This is a nice UX improvement, I'm adding this to our Next Sprint queue but no immediate ETA on when this will be done.

**Comment by kirtangajjar** [comment]
@jeffpaul @faisal-alvi It looks like this issue has already been resolved
![Screenshot from 2023-03-17 14-40-26](https://user-images.githubusercontent.com/8456197/225863012-6379dd28-7f68-41a0-993c-9cd40d4ab7bd.png)
![Screenshot from 2023-03-17 14-41-03](https://user-images.githubusercontent.com/8456197/225863057-6c2e531d-1836-464e-9baf-2b2fbc60481c.png)

**Comment by jeffpaul** [comment]
@Brianmitchtay will you please confirm that you see this working as expected now?

**Comment by Brianmitchtay** [comment]
With Accommodation Bookings Version 1.1.39 and Bookings Version 1.15.76 this is what I'm seeing.

![lcvkG6.png](https://user-images.githubusercontent.com/45057772/225972563-a856c544-957a-46ce-8744-6b5e8614e2be.png)

So this doesn't seem resolved AFAICT. Reviewing the strings in Loco Translate it looks to me like this is coming from the core bookings extension and there's nothing in the Accommodations extension that overrides it. Not sure if I have my head totally wrapped around how that works though.

**Comment by Sidsector9** [comment]
@kirtangajjar I am able to reproduce this with:

- Accommodation Bookings Version 1.1.39
- Bookings Version 1.15.76 - 1.15.78

Let me know when you're available for a call, I'll guide you.
