### ISSUE TITLE
Feature Request: allow flexible minimum number of nights

### ISSUE THREAD

**Issue by solaceten** [woocommerce/woocommerce-accommodation-bookings#33]
Minimum number of nights allowed in a booking is currently fixed to one field (e.g. 1 night)

It would be great if it could be possible to be able to add Minimum number of nights according to dates - e.g. December 20th - January 10th:  minimum number of nights = 2

**Comment by jamiebudesky** [comment]
Also to require a minimum number of nights including a specific day. Example: Sunday - Thursday require 1 night. Friday & Saturday require 2 nights. So if a guest wants friday night. they are required to book at least 1 more additional day like thursday or saturday. but if customer wants only thursday night, can book 1 night.  This is a feature similar on airbnb. 

![unspecified-1](https://cloud.githubusercontent.com/assets/9441884/14235777/d9d16c36-f9d5-11e5-840f-c8d3edb0d070.png)

**Comment by siderlan** [comment]
Hi guys, I'm looking for this feature.
What is its status?

**Comment by melindahelt** [comment]
Adding another vote for the ability to set different minimum nights for Weekend vs Weekday reservations.

**Comment by muzo178** [comment]
Another vote to be able to add minimum number of nights according to date ranges

**Comment by DustinHartzler** [comment]
In a WooCierge session (959551-zen), this was brought up as well.

They want to make sure that if a Friday or Saturday night was booked, that it required a two night stay, but if a Wednesday or Thursday was selected, they could offer the option of one night only.

**Comment by laurendavissmith** [comment]
Moved to the ideas board
