### ISSUE TITLE
Missing Date Picker in Cost Setting Tab

### ISSUE THREAD

**Issue by ankitguptaindia** [woocommerce/woocommerce-accommodation-bookings#330]
The date picker option is not appearing in the 'Rates' tab of the Accommodation product when editing or adding a new product.
Store owners only put dates by adding manually from keyboard.

![image](https://user-images.githubusercontent.com/6384299/217552002-f386ae4d-cdc0-46bb-ad43-8f6fa9a305f0.png)

### Steps to Reproduce:

1. Enable the Booking Accommodation extension.
2. Navigate to the 'Add New Product' or 'Edit Existing Accommodation Product' page.
3. Select the 'Accommodation product' option from the Product Data drop-down.
4. Go to the 'Rates' tab and select 'Range of Certain Nights'.
5. Observe that there is no option to select dates in the Starting/Ending fields.

#### Affected ticket(s)

N/A - this is a QA finding. 

### Expected Result:
The date picker option should be available in the 'Rates' tab to allow users to select dates for the Starting/Ending fields.

### Environment

Browser- Chrome Version 109.0.5414.119 
OS - macOS Monterey V 12.3.1

<Details>

`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: Asia/Kolkata
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 39
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/ank/Local Sites/woolocal/app/public
wordpress_size: 43.74 MB (45864821 bytes)
uploads_path: /Users/ank/Local Sites/woolocal/app/public/wp-content/uploads
uploads_size: 245.18 MB (257094621 bytes)
themes_path: /Users/ank/Local Sites/woolocal/app/public/wp-content/themes
themes_size: 11.49 MB (12043630 bytes)
plugins_path: /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins
plugins_size: 2.25 GB (2415956491 bytes)
database_size: 115.63 MB (121241600 bytes)
total_size: 2.66 GB (2852201163 bytes)

### wp-active-theme ###

name: Storefront (storefront)
version: 4.2.0
author: Automattic
author_website: https://woocommerce.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, custom-logo, menus, html5, custom-background, custom-header, site-logo, title-tag, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-style, responsive-embeds, amp, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, starter-content, widgets
theme_path: /Users/ank/Local Sites/woolocal/app/public/wp-content/themes/storefront
auto_update: Enabled

### wp-plugins-active (5) ###

Bookings Helper: version: 1.0.3, author: WooCommerce, Auto-updates disabled
WooCommerce: version: 7.3.0, author: Automattic, Auto-updates disabled
WooCommerce Accommodation Bookings: version: 1.1.37, author: WooCommerce, Auto-updates disabled
WooCommerce Blocks: version: 9.5.0, author: Automattic, Auto-updates disabled
WooCommerce Bookings: version: 1.15.75, author: WooCommerce, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 21.4.0 x86_64
httpd_software: nginx/1.16.0
php_version: 8.0.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.54.0 LibreSSL/2.6.5
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.28
client_version: mysqlnd 8.0.0
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/ank/Local Sites/woolocal/app/public/wp-content
WP_PLUGIN_DIR: /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

`

</Details>

**Comment by ankitguptaindia** [comment]
@vikrampm1 Please assign this for the next step.

cc: @jeffpaul

**Comment by faisal-alvi** [comment]
@ankitguptaindia, it appears that there is already a date picker field present, but it lacks borders. I will proceed with adding borders to it but I'm curious if it was there in the past. If so, when did it disappear? Which version of bookings/accommodation/WooCommerce/WordPress was it present in?

![330-02](https://user-images.githubusercontent.com/25176325/218059336-f9c2d8e0-85e3-4480-bd86-4dc1e7a4236c.gif)

**Comment by jeffpaul** [comment]
@faisal-alvi not sure that its super relevant WHEN things stopped being there (for that matter, maybe they never were?).  A PR to resolve will be most helpful at this point.

**Comment by faisal-alvi** [comment]
@jeffpaul Sure! I'll raise a PR. I am changing the priority from High to Low as this is not harming the bookings flow. Please change it back to High if required.

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64


</Details>


Tested with Archive File created via 

```php woorelease.phar build https://github.com/woocommerce/woocommerce-bookings/tree/smoke-testing```

- Composer version - 2.3.5
- npm version - 6.14.15
- node version - v14.18.0

#### Please note that this plugin is tested with the build created by specified versions of Composer, Node, and NPM. 



**Status-**. Ready to Merge 🚀
