### ISSUE TITLE
Compatibility testing with WooCommerce 7.6 RC and WordPress 6.2 RC

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-accommodation-bookings#331]
With WooCommerce 7.6 RC 1 and WordPress 6.2 RC 1 releases out, perform the following:

- [ ] Test the extension thoroughly with WC 7.6 and WP 6.2
- [ ]  Add compatibility fixes, where necessary
- [ ]  Bump WooCommerce "Tested up to" to 7.6
- [ ]  Bump WooCommerce minimum to 6.8
- [ ]  Bump WordPress "Tested up to" to 6.2
- [ ]  Bump WordPress minimum to 5.8
- [ ]  Scan for any conditional checks that may be in the code that can be removed with this "Tested up to" and minimum bumps

Sample Changelog entry should then be:
> Dev - Bump WooCommerce minimum supported version from X.X to 6.8.
> Dev - Bump WooCommerce "tested up to" version 7.6.
> Dev - Bump WordPress minimum supported version from X.X to 5.8.
> Dev - Bump WordPress "tested up to" version 6.2.

**Comment by ankitguptaindia** [comment]
@jeffpaul As WC 7.7.0 has been already released. Can we create this new PR directly for WC 7.7.0? 

cc: @kirtangajjar @vikrampm1

**Comment by vikrampm1** [comment]
@ankitguptaindia for WC 7.7 we will be only testing Bookings, Square and Deposits. When WC 7.8 gets released then we will do compat tests across all the extensions so I think it's fine to continue with 7.6 on this for now.
