### ISSUE TITLE
Latest release (1.1.40) broke calendar display on Divi Visual Builder

### ISSUE THREAD

**Issue by bpfh** [woocommerce/woocommerce-accommodation-bookings#339]
#### Affected ticket(s)

#6330814

#### What I expected

Booking start and end dates in the calendar are displayed with the partial_booked class if there are no adjacent bookings.

#### What happened instead

This class is no longer present. See the screenshot:

<img width="436" alt="image" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/822210/fb757774-1c22-4f1c-9400-8e796114f272">

There is a booking from 19 Aug - 20 Aug, and no partial_booked class is present.

#### Steps to reproduce the issue

* Upgrade to 1.1.40 release
* Create a one-night booking with free availability on both sides
* The calendar shows no indication that there even is a booking for this one night

Workaround: downgrade back to [version 1.1.39](https://github.com/woocommerce/woocommerce-accommodation-bookings/releases/tag/1.1.39)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ravinderk** [comment]
@bpfh This is expected behavior. We recently updated UI/UX: https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303. You will see a message when you hover over partially booked dates. 

Let me know if you have any questions.

**Comment by bpfh** [comment]
Thanks @ravinderk !

The UX change in itself seems good, but unfortunately, I cannot get it to work. Even after updating the plugin, I get the same old messages when hovering, and the DOM does not seem to have any CSS classes that I could use. I recently managed to achieve the holy grail of booking calendars (the diagonal red/green blocks) using rather unwieldy CSS, and obviously this would be much easier to implement if the information for "available for check-in" and "available for check-out" were somehow indicated in the DOM or elsewhere.

I must be missing something obvious :(

<img width="572" alt="image" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/822210/50b18282-c181-4bdb-816d-f6edebd51015">

**Comment by bpfh** [comment]
Scratch the above. I switched to the default theme and I can see at least the custom classes. My Divi based theme must be doing something ugly to the calendar display.

**Comment by ravinderk** [comment]
@bpfh Can you that you are using the latest booking add-on?

**Comment by bpfh** [comment]
Yes, everything is the latest.

For posterity: if the product page is build using Divi Visual Builder, it screws up the calendar display somehow, removing the new and helpful classes fully_booked_start_days and fully_booked_end_days. How it does this is a bit of a mystery.

If I let WooCommerce to lay out the product page, everything works as specified. I just need to do the necessary customisations via PHP and CSS to get a neat result.

Feel free to close this issue. With honours!
