### ISSUE TITLE
Compatibility with WooCommerce Payments

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-accommodation-bookings#351]
Check if this extension is compatible with WooCommerce Payments - Any storefront using this extension should integrate & work with WooCommerce Payments for the payment portion.

https://woocommerce.com/products/woocommerce-payments/

- [ ] Test the extension's compatibility with WC Payments thoroughly
- [ ] Add compatibility fixes, where necessary
- [ ] Add a note to the README.md that the extension is compatible

**Comment by peterwilsoncc** [comment]
**Smoke testing**

- [x] [Plugin Activation Without Errors](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#plugin-activation-without-errors)
- [ ] ~[Can see a message when the core plugins WooCommerce & WooCommerce Booking are not active](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#can-see-a-message-when-the-core-plugins-woocommerce--woocommerce-booking-are-not-active)~ _Bug found, unrelated to payments, https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/374_
- [x] [Plugin Setup and Configuration Screen](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#plugin-setup-and-configuration-screen)
- [x] [Can create an Accommodation product](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#can-create-an-accommodation-product)
- [x] [Verify Accommodation Time Setting - Check-in and Check-out.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-accommodation-time-setting----check-in-and-check-out)
- [x] [Verify labels 'Select check-in' and 'Select check-out' works expected.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-labels-select-check-in-and-select-check-out-works-expected)
- [x] [Verify Setting Minimum Nights Restriction - "Minimum number of nights allowed in a booking"](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-setting-minimum-nights-restriction---minimum-number-of-nights-allowed-in-a-booking)
- [x] [Verify Setting Maximum Nights Restriction "Maximum number of nights allowed in a booking"](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-setting-maximum-nights-restriction-maximum-number-of-nights-allowed-in-a-booking)
- [x] [Verify the Number of Rooms Availability](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-the-number-of-rooms-availability)
- [x] [Verify Calendar DisplayMode - Display Calendar on Click](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-calendar-displaymode----display-calendar-on-click)
- [x] [Verify Calendar Display Mode Setting - Always Visible](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-calendar-display-mode-setting---always-visible)
- [x] [Verify Accommodation Booking Creation with Confirmation Setting](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-accommodation-booking-creation-with-confirmation-setting)
- [x] [Verify Accommodation Booking Process for Slot Requiring Confirmation](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-accommodation-booking-process-for-slot-requiring-confirmation)
- [ ] [Check for "Can be cancelled" Setting](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#check-for-can-be-cancelled-setting)
   - Can only be done if the user has an account, no link for doing so in email. Expected?
   - Cancellation email after the customer cancels says "We are sorry to say that your booking could not be confirmed and has been cancelled. The details of the cancelled booking can be found below." -- incorrect given the user has cancelled it
- [x] [To verify the maximum room availability setting.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#to-verify-the-maximum-room-availability-setting)
- [x]  [Availability > Bookings Can Be Made Starting - Month/Week/Day - in the Future Setting](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#availability--bookings-can-be-made-starting---monthweekday---in-the-future-setting)
- [x] [Availability > Booking Can Be Booked Till Setting](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#availability--booking-can-be-booked-till-setting)
- [x] [Verify 'Rates' Setting for Accommodation Booking](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-rates-setting-for-accommodation-booking)
- [x] [Verify 'Rates' Setting for Accommodation Booking with Range Types with Range Type 'Range of certain night'.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-rates-setting-for-accommodation-booking-with-range-types-with-range-type-range-of-certain-night)
- [x] [Verify 'Rates' Setting for Accommodation Booking with Range Types with Range Type 'Range of months'.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-rates-setting-for-accommodation-booking-with-range-types-with-range-type-range-of-months)
- [x] [Verify Booking Details Check-In and Check-Out Date and Time Display.](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-booking-details-check-in-and-check-out-date-and-time-display)
- [x] [Verify Accommodation Booking Details in Confirmation Emails](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-accommodation-booking-details-in-confirmation-emails)

**Comment by peterwilsoncc** [comment]
Payments Specific tests:

* [ ] [Verify Accommodation Booking Creation with Confirmation Setting](https://github.com/woocommerce/woocommerce-accommodation-bookings/wiki/Testing-instructions-for-critical-flows#verify-accommodation-booking-creation-with-confirmation-setting)
   - Variation: WooCommerce Payments set to "Issue an authorization on checkout, and capture later"
   - Test: Does the checkout capture the credit card for automatic processing following confirmation?
   - Result: It does not, **should it?**
* [x] Google Pay button is [not shown on product page](https://woocommerce.com/document/woopayments/payment-methods/google-pay/#product-compatibility)
* [x] Apple Pay button is [not shown on product page](https://woocommerce.com/document/woopayments/payment-methods/apple-pay/#product-compatibility)
* Booking requiring confirmation -- these are not charged until the store admin confirms them
   * [x] Apple Pay button completely unavailable
   * [x] Google Pay button completely unavailable
* Express pay buttons appear on cart
   * [ ] Apple Pay
   * [ ] Google Pay
* Express pay buttons appear on checkout
   * [ ] Apple Pay
   * [ ] Google Pay
* ~Bookings are created with order~
   * ~[ ] Apple Pay~
   * ~[ ] Google Pay~
   * _N/A Given above failures*_

_*_ I'm not sure if these are failures or expected behaviour. The WooPayments docs mention that bookable products are compatible with Google and Apple Pay but it does not specifically mention that _Accommodation bookable products_ are compatible with the services.
