### ISSUE TITLE
Product Add-ons compatibility - price * nights

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-accommodation-bookings#37]
WooCommerce Bookings has a checkbox to select to multiply the add-on cost per the number of blocks.
This does not exist in Accommodation Bookings, neither is done automatically.

Can we add the feature like in WooCommerce Bookings?

**Comment by RookDesigns** [comment]
This would basically make me buy Woocommerce bookings instead of Booking System Pro. Resources and people aswell

**Comment by robertstaddon** [comment]
I think that this goal could be accomplished if this plugin was coded to support the built-in WooCommerce Bookings Resources (https://docs.woothemes.com/document/using-global-resources/). Resources are limited to available quantities and can be multiplied by the number of blocks booked.

**Comment by robertstaddon** [comment]
I've created a pull request that would allow Accommodations products to use the Resources feature of WooCommerce Bookings. https://github.com/woothemes/woocommerce-accommodation-bookings/pull/40

**Comment by studioviv** [comment]
I totally agree with RookDesigns. We are also following progress on this feature for WCBookings and AccommodationBookings. It would make us also go from Booking System Pro to Woocommerce bookings. I like the fact that all is related to WC and the whole payment/invoicestructure so i would prefer it above any other.
But the fact that we can't use use acc.bookings with personscount and WCBookings lacks the overnight stay option we cannot switch. It so much more logic to have overnight option in WCBookings cause that counts for every hostel, hotel, campingsite, bnb etc. We need to be able to book  1 room from lets say 14th to 20th and the next person should be able to book from 20th to whatever.
And not from 21th, that's missing 1 whole booking. Guests go out at 10.00 and new ones come in at 14.00 < that's logic procedure.

**Comment by SiR-DanieL** [comment]
@gedex any update on this?

**Comment by gedex** [comment]
Sorry for late reply. I haven't check this. Definitely on our queue, but I don't have exact ETA to announce yet.

/cc @mattyza @dwainm

**Comment by jamiebudesky** [comment]
This is defiantly a need for our campground so we can charge additional for Wifi per night. Also without resources and people, this plugin is not much different than a bookable product. Hope 1.0.3 will include these features.

**Comment by emma164** [comment]
I agree that this is a definite need, just to be able to multiply the **product-addons total** by the **duration**. I have been looking into the code and I can't find where the product-addons are added to the booking price? has anyone any ideas please.

**Comment by robertstaddon** [comment]
@emma164, @jamiebudesky, @SiR-DanieL, @studioviv, and @RookDesigns 

I have modified the plugin to support Resources, Persons, and Product Add-ons and submitted a Pull Request to the developers for a 1.0.4 version: https://github.com/woothemes/woocommerce-accommodation-bookings/pull/40

If you would like to download my fork at https://github.com/robertstaddon/woocommerce-accommodation-bookings and take it for a spin, I would really appreciate any feedback that you might have.

**Comment by mattyza** [comment]
@gedex @dwainm @roykho :)

**Comment by al3xstanhope** [comment]
Sounds brilliant, @robertstaddon - good work!

Just need some bright spark out there to come up with an easy way to input multiple "seasonal" rates with different prices on weekdays and weekends and this plug-in will be perfect!

**Comment by jamiebudesky** [comment]
Completely agree!

**Comment by robertstaddon** [comment]
Hey guys! It appears that my 1.0.4 pull request has been merged. (https://github.com/woothemes/woocommerce-accommodation-bookings/pull/40)  It's not live on the WordPress repository yet, but if any of you want to try downloading it from here on GitHub and testing the use of Resources or Persons on your site, any feedback would be great! Thanks.

**Comment by silicondales** [comment]
Works great with addons multiplying price of addon per night.

**Comment by laurendavissmith** [comment]
Moved to the ideas board for further evaluation
