### ISSUE TITLE
Is find-booked-day-blocks nonce required?

### ISSUE THREAD

**Issue by rtpHarry** [woocommerce/woocommerce-accommodation-bookings#373]
#### What I expected

(Sorry, I know this is really an issue with woocommerce-bookings, not this sub plugin, but there is no access to the woocommerce-bookings repo available and trying to do support through the woocommerce.com live chat style interface doesn't give me access to anyone that really understands technicalities of issues)

There have been ongoing issues with this plugin with the booking availability calendar just showing a spinner. 

It is caused by the `find-booked-day-blocks` nonce expiring, but the page still being cached.

I had solved this on the previous host by making the cache live for under 12 hours.

I'm on a new host now which is more premium host to handle the traffic, but has a different cache system which is more restrictive.

Basically the issue seems to be that the REST call to get the available slots has a nonce security check on it. The cache lives longer than the nonce is valid, so the rest call returns a 403 error.

I don't really know why the rest call has a nonce check on it though? It is a public facing, select-style, idempotent query. It is not submitting anything, or requiring any admin privileges. 

It just seems to cause problems, and not achieve anything.

The current hosts solution has required me to disable a large portion of their caching system, site wide, to work around this issue.

As the nonce check doesn't seem to achieve anything it would solve all my problems to skip this check, but I cannot get to this line to edit it.

It would be great to either remove it, if you agree with my point that it does nothing, or at least wrap it in a filter to let it be optionally disabled by code.

I have seen a similar solution to this implemented, allowing it to be optionally disabled, in Jet Form Builder, which lets you toggle the nonce check on a per-form basis.

#### What happened instead

403 errors on the rest call

#### Steps to reproduce the issue

1. Cache the page
2. Wait until the nonce has expired, but the cache hasn't
3. See the spinner, see 403 error in the dev console

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by fscriven** [comment]
Should definitely have the option to remove. Search around the internet and you'll see hundreds of problems related to this. And the solutions are normally remove ESI, remove caching from product pages, remove caching completely, refresh cache every x hours, etc. Why should users of this software have to sacrifice proper caching to use it?

**Comment by faisal-alvi** [comment]
Noting a related ticket in the core: https://core.trac.wordpress.org/ticket/46365

**Comment by faisal-alvi** [comment]
@rtpHarry I've raised a PR introducing a filter in the WooCommerce Bookings repository.

To disable the nonce check, you'll be able to add the following filter to your theme or plugin once the PR is merged and released:

```
add_filter( 'disable_find_booked_day_blocks_nonce_check', '__return_true' );
```

**Comment by rtpHarry** [comment]
Thank you for implementing this!
