### ISSUE TITLE
Plugin fatals if Bookings active but WooCommerce is not.

### ISSUE THREAD

**Issue by peterwilsoncc** [woocommerce/woocommerce-accommodation-bookings#374]
The Accommodation Bookings plugin checks that the Bookings extension is active but does not account for the situation in which Bookings is active but WooCommerce core is not.

#### What I expected

When neither Bookings or WooCommerce active:
* a notice the plugin requires bookings
* a notice the plugin requires WooCommerce

When Bookings is active, WooCommerce is not:
* a notice the plugin requires WooCommerce 

When WooCommerce is active, Bookings is not:
* a notice the plugin requires Bookings

#### What happened instead

When neither Bookings or WooCommerce active:
* a notice the plugin requires bookings
* _no notice re: WooCommerce core_

When Bookings is active, WooCommerce is not:
* **_a fatal error_**
   ```
   [02-Oct-2023 00:08:03 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Settings_API' not found in /vagrant/content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-product-settings.php:8
   Stack trace:
   #0 /vagrant/content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-bookings-plugin.php(209): include()
   #1 /vagrant/wp-build/wp-includes/class-wp-hook.php(310): WC_Accommodation_Bookings_Plugin->admin_includes('')
   #2 /vagrant/wp-build/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
   #3 /vagrant/wp-build/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
   #4 /vagrant/wp-build/wp-settings.php(632): do_action('init')
   #5 /vagrant/wp-config.php(146): require_once('/vagrant/wp-bui...')
   #6 /vagrant/wp-build/wp-load.php(55): require_once('/vagrant/wp-con...')
   #7 /vagrant/wp-build/wp-admin/admin.php(34): require_once('/vagrant/wp-bui...')
   #8 /vagrant/wp-build/wp-admin/plugins.php(10): require_once('/vagrant/wp-bui...')
   #9 {main}
     thrown in /vagrant/content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-product-settings.php on line 8
   ```

When WooCommerce is active, Bookings is not:
* a notice the plugin requires Bookings, _as expected_

#### Steps to reproduce the issue

1. Activate WooCommerce
2. Activate WooCommerce Bookings
3. Activate WooCommerce Accommodation Bookings
4. Deactivate WooCommerce
5. Observe fatal error: `PHP Fatal error:  Uncaught Error: Class 'WC_Settings_API' not found` per stack trace above

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by faisal-alvi** [comment]
Seems to be a duplicate of #363 (PR #367)

**Comment by peterwilsoncc** [comment]
> Seems to be a duplicate of #363 (PR #367)

Agreed, sorry about that.
