### ISSUE TITLE
Booking cost does not recalculate when changing number of persons.

### ISSUE THREAD

**Issue by aamoccia** [woocommerce/woocommerce-accommodation-bookings#375]
#### What I expected

When changing the number of persons after selecting the booking dates, the booking cost should recalculate.

#### What happened instead

Booking cost remains the same and reflects the cost based on the initial number of persons. Once item is added to the cart, the correct booking cost is calculated.

#### Steps to reproduce the issue

1. Ensure Woocommerce Bookings (v2.0.0) and WooCommerce Accommodation Bookings (v1.2.0) plugins are installed.
2. Import the accommodation product from the zip file: [wc-product-export-1-10-2023.csv.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/12778516/wc-product-export-1-10-2023.csv.zip)
3. Select check-in and check out booking dates.
![SelectDates](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/106126627/74d1162b-c184-48be-abf6-953d43c7ca4e)
4. Change the number of adults and children. Note booking cost does not recalculate.
![ChangePersons](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/106126627/35243746-7b4b-4127-a4c2-72d9652d34bf)
5. Select book now. Note correct booking cost appears in the cart.
![CorrectCost](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/106126627/a64c2ba4-0b30-4b84-aead-074f1405c7b3)

Customer wants to customize product page by moving the date picker above the number persons. This issue was discovered when testing this change on a staging site. This issue appears to be limited to accommodation products (bookable products do not exhibit this issue).

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thisissandip** [comment]
8049726-zen

**Comment by thisissandip** [comment]
This bug is present within WooCommerce Bookings itself, it occurs when you have enabled the "Calendar range picker", I have created a separate issue for this: https://github.com/woocommerce/woocommerce-bookings/issues/3815

**Comment by thisissandip** [comment]
8397820-zen
