### ISSUE TITLE
Test Compatibility and Integration with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-accommodation-bookings#390]
Test compatibility and integration with block based checkout and full site editing with the following tasks:

- [ ] Compatible - Each extension is fully compatible with Cart and Checkout Blocks and the new WooCommerce 8.3 default WordPress Site Editing (aka “Store Editing”) and doesn't break/fail when Store Editing is used (but may use shortcodes for output).  
- [ ] Integration - Each extension integrates natively with Cart and Checkout Blocks and Store Editing (uses blocks, provides no-code customization options, etc).
- [ ] Investigate and add any missing e2e test cases to cover Cart and Checkout Blocks.
- [ ] Add compatibility and integration fixes, where necessary.

**Comment by Sidsector9** [comment]
- [x]  Block Checkout works as expected
- [x]  Block Cart works as expected
- [x]  Store editing works as expected

---

- ✅  The Cart and Checkout Blocks display all the necessary information related to the Booking product and line item meta

---

- The plugin does not have any shortcodes
- Investigating further, I did not find any more features that needs support on the Cart and Checkout block pages.

---
