### ISSUE TITLE
REST API accomodation-booking product creation not possible

### ISSUE THREAD

**Issue by axi** [woocommerce/woocommerce-accommodation-bookings#401]
#### What I expected

Being able to create an Accomodation booking through API.

There's no ```WC_Accomodation_Bookings_REST_Products_Controller``` so we have to use ```WC_Bookings_REST_Products_Controller``` which could be fine if method ```prepare_object_for_database()``` was not enforcing ```$request['type'] = 'booking'```.

#### What happened instead

It enforces type booking so my products ends up "Bookable products" and not "Accomodation products". 

#### Steps to reproduce the issue
```php
$request = [
    'name' => 'new product name', 
    // more properties
];
$wpRequest = new WP_REST_Request('POST');
$request['type'] = 'accommodation-booking'; // to create a WC_Product_Accommodation_Booking
$wpRequest->set_body_params($request);

$controller = new WC_Bookings_REST_Products_Controller();
$result = $controller->create_item($wpRequest);
```
=> ```$result['type'] === 'booking'```

I guess it's more a woocommerce-bookings bug but it's so related to this one I tried my chance here.

If instead of using ```WC_Bookings_REST_Products_Controller```, we use ```WC_REST_Products_Controller```, the product class is the right one (but with none of the product customization done in ```WC_Bookings_REST_Products_Controller::prepare_object_for_database()``` method

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by axi** [comment]
A simple correction in WC_Bookings_REST_Products_Controller::prepare_object_for_database() method would do the trick (line 183)
```php
		$request['type'] = $request['type'] ?? 'booking';
```

**Comment by ankitguptaindia** [comment]
This issue is a blocker to test PR https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/425

**Comment by faisal-alvi** [comment]
More info about the issue: https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/435#issue-2313206689

**Comment by axi** [comment]
Does this issue can have an impact on woocommerce-booking ? I mean, does some people from "proprietary" woocommerce-booking also works on this repo ? I have had no chance with submiting support tickets to woocommerce-booking team (or at least no return saying it's fixed...) and no releases fixing it.

**Comment by faisal-alvi** [comment]
@axi Thanks for your report and patience. We are working on this and will fix it as soon as possible.

**Comment by faisal-alvi** [comment]
The PRs raised:

- https://github.com/woocommerce/woocommerce-bookings/pull/3809
- https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/436

**Comment by axi** [comment]
I can't access the woocommerce-bookings PR but I'm glad things are moving, thanks @faisal-alvi

**Comment by axi** [comment]
I see that woocommerce-booking 2.1.4 release modified the 

```php
	protected function prepare_object_for_database( $request, $creating = false ) {
		$request['type'] = 'booking';
		...
	}
```
to
```php
	protected function prepare_object_for_database( $request, $creating = false ) {
		$request['type'] = empty( $request['type'] ) || 'simple' === $request['type'] ? 'booking' : $request['type'];
		...
	}
```
Thanks to whom worked on that

**Comment by axi** [comment]
@faisal-alvi 
I also realised I had to add a check to return the potential parent wp_error.
`wp_send_json()` way looks like a non-conventional way to terminate the process and prevent from extending correctly this class... (I know it's a woocommerce-booking problem).
I searched for other `prepare_object_for_database()` and it looks like this is the only implementation doing that (I only have few WC plugin installed). Any thoughts ?

```php
protected function prepare_object_for_database( $request, $creating = false ) {
    $request['type'] = empty( $request['type'] ) || 'simple' === $request['type'] ? 'booking' : $request['type'];

    $product =  parent::prepare_object_for_database( $request, $creating );

    // ADDED
    if ( is_wp_error( $product ) ) {
        return $product;
    }
    // / ADDED

    if ( ! $product instanceof WC_Product_Booking ) {
        wp_send_json( __( 'Not a bookable product', 'woocommerce-bookings' ), 400 );
    }
    ...
}
``

**Comment by faisal-alvi** [comment]
@axi Thank you for your suggestion. We appreciate your input. However, the current approach ensures specific type checking for `WC_Product_Booking` and maintains consistency across our implementation. While the use of `is_wp_error( $product )` can offer flexible error handling, it does not provide the specific type checking necessary for our operations. Additionally, our user base has not indicated a widespread need for this change, so we believe that the current implementation serves the majority of our users effectively.

We understand that different use cases may require different approaches, and we are always open to considering future enhancements based on user needs. If you have any other suggestions or if there are specific issues you're encountering that prompted this request, please let us know.

**Comment by axi** [comment]
There is a specific issue that made me add this lines (I usualy do not debug for fun), I just have to find which one :-) I'll do my homework and come back here or open a new PR / Issue

**Comment by axi** [comment]
Ok found it:
in function.php:
```
add_filter(
    hook_name: 'woocommerce_rest_pre_insert_product_object',
    callback: static function () {
        return new WP_Error(
            "Product names cannot contain the letter u (on theresnoletterbetweenTandV.com)"
        );
    },
    accepted_args: 0
);
```
This looks valid to me because ```prepare_object_for_database()``` method documents a ```@return WP_Error|WC_Data``` and is declared protected. We should be able to extend it and expect it to be able to propagate up a ```WP_Error```.

In my proposal above, It won't prevent the existing check `(! $product instanceof WC_Product_Booking)`, just allows returning a custom error before executing your existing check. The existing check clearly is here to prevent using this controller to update some other kind of products (see wording) and will still be fine with my modification.

Regarding your comment on the current implementation serving the majority of your users, until this ticket was close, it was quite hard to create an accomodation-booking threw API so  that might have been discouraging people from doing some custom implementation or extending the `WC_Bookings_REST_Products_Controller`. Now this is fixed, people might start doing so and will face this same problem.

**Comment by axi** [comment]
If I had the woocommerce-booking source code, I would launch the unit tests with my modification to see if this breaks something (but I don't). I'm almost sure it doesn't.

**Comment by axi** [comment]
Hi @faisal-alvi, just making sure my last comments were read and hopefully advocate in favor of allowing returning a Wp_Error.

**Comment by jeffpaul** [comment]
@axi the [Bookings extension](https://woocommerce.com/products/woocommerce-bookings/) is a premium/paid one and purchasing the extension is the best way to access the codebase.  If there are specific questions you have about extending Bookings, then please ask those and we'll do what we can to assist.

**Comment by axi** [comment]
@jeffpaul I do use the booking extension, and therefore I have the plugin code base, but not the source (with tests), that's what I meant. And I find their zendesk based support helpless for those precise usecases where you want to share code, offer PR or fill issues... I did open an issue on this specific case (7797316) but it seems it led nowhere. I just tried replying to the ticket again

**Comment by jeffpaul** [comment]
@imodouglas can you help pull in context from 7797316 to see if there's more that can be done here?

**Comment by axi** [comment]
It looks like when I replied to 7797316 it opened a new ticket [8631924](https://woo.zendesk.com/hc/requests/8631924)
