### ISSUE TITLE
Seasonal Rates

### ISSUE THREAD

**Issue by al3xstanhope** [woocommerce/woocommerce-accommodation-bookings#42]
To the team at WooCommerce Accommodation Bookings,

First off, congratulations on putting together such a fantastic extension to the Bookings plug-in; super easy to use, and confers some much-needed functionality for property owners with minimal hassle. I for one certainly hope that this project keeps rolling for the forseeable future as it really is handy!

I did have one question about the "Rates" settings in connection with a particular use case for a project we're going to be working on here shortly. However, the use case itself is by no means unique to our project and I am sure that others would like a similar feature to be in place too.

In this instance, the property has two seasonal rates (High/Low) which are based on months (simple enough with the existing plug-in version), but the kicker is that there are weekday and weekend rates within these, which doesn't appear to be quite so easy to implement. An example is shown below for your reference:

High Season (April to December)

£205 Weekend (Friday – Sunday)
£185 Weekday (Monday – Thursday)

Low Season (January – March)

£185 weekend (Friday – Sunday)
£165 weekday (Monday – Thursday)

Any ideas on how something like this could be set up as things stand with the current version? Or are there plans afoot to add conditions to "Rates" pricing such as "if", "and", "or" and so on?

Look forward to hearing your thoughts!

Alex

**Comment by robertstaddon** [comment]
@al3xstanhope This is a great idea! The functionality you are mentioning would be appropriate for a wide variety of booking types, which means it would be a better fit for the WooCommerce Bookings plugin. Any changes implemented in that plugin could then be easily made to take effect on this plugin, which merely extends Bookings to optimize it for use with accommodations. 

I noticed your idea being discussed quite a bit in relation to the WooCommerce Bookings plugin in the comments of this WooThemes article: https://support.woothemes.com/hc/en-us/articles/202227913-Can-I-have-a-different-price-for-weekends-

Based on that discussion, the following idea was submitted as a feature request for WooCommerce on the WooIdeas board: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/7014952-better-repeating-costs-dates-for-woobookings

I think your best shot at getting this implemented into WooCommerce Bookings would be to vote for it on the Ideas board and perhaps add your comment to the above article.

**Comment by silicondales** [comment]
+1 for this one. Working on a project which requires this and will in all likelihood code something up. Will try to remember to post a snippet back here in return for a virtual high five :)

**Comment by silicondales** [comment]
I'm going to post the (simple) solution which am likely to go with in our use case: set a zero price, and then use date ranges to achieve your pricing goals. In our case, we had monthly seasonals, plus "bank holiday" weekend pricing. So not every weekend (camp site for motorhomes, and shut during winter) but thought worth mentioning.

piccy below

![woocommerce-bookings-accommodation-seasonal-weekend-pricing-setup](https://cloud.githubusercontent.com/assets/17259256/16568812/7cafc342-4226-11e6-854b-b695f2707be5.jpg)

**Comment by silicondales** [comment]
An alternative would be to set your minimum price (i.e. £165) then put the extra cost in for the dates concerned (i.e. £40 for each high season weekend, £20 high season week day, and so on).

**Comment by laurendavissmith** [comment]
We moved this idea to the ideas board
