### ISSUE TITLE
Admin writepanel script not found

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-accommodation-bookings#428]
The rates cannot be reordered because the writepanel.min.js script is not found.

<img width="793" alt="Captura de pantalla 2024-05-14 a las 10 16 40" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/28978793/48e9baa5-3ebe-46d4-b4b0-5a825a700509">

The sort function does not work because the script is not found:

<img width="1044" alt="Captura de pantalla 2024-05-14 a las 10 16 53" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/28978793/55d85b0b-0d42-4afb-b7ba-fe9ebaf7d441">

In the file class-wc-accommodation-booking-admin-panels.php the constant SCRIPT_DEBUG is being checked. The result is that the script should have the suffix 'min' but then it turns out that the writepanel.min.js file does not exist in the project.

<img width="2322" alt="Captura de pantalla 2024-05-14 a las 10 19 07" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/28978793/836b76d1-6817-42a1-b8fa-e76291dcb38e">

<img width="424" alt="Captura de pantalla 2024-05-14 a las 10 21 55" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/28978793/94f13ef6-18a3-4452-a0d3-9b638cf8a9c7">

**Comment by MiguelAxcar** [comment]
@vikrampm1 this issue was already fixed by this commit on May 21:
https://github.com/woocommerce/woocommerce-accommodation-bookings/commit/5a3e162cbe721b03b961246d17a0a406b72f113d#diff-fc90253d03a08aaf170c6cb29c1df77c9219575d826f5bfe5da97eccdadfad58

**Comment by jeffpaul** [comment]
@MiguelAxcar so seems like we can close this issue via #433 and the 1.2.7 milestone/release?

**Comment by MiguelAxcar** [comment]
> [@MiguelAxcar](https://github.com/MiguelAxcar) so seems like we can close this issue via [#433](https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/433) and the 1.2.7 milestone/release?

Yes @jeffpaul - I added this issue as being closed by https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/433 on PR description.
