### ISSUE TITLE
Test Compatibility of WooCommerce Extensions with Translation Loading Changes in WordPress 6.7

### ISSUE THREAD

**Issue by Sourabh208** [woocommerce/woocommerce-accommodation-bookings#480]
WordPress 6.7 introduces updates to how translations are loaded. These changes may impact WooCommerce extensions that rely on localized strings. To ensure compatibility, we need to test all extensions to verify that translations load correctly without errors.

[Developer advisory: Translation loading changes in WordPress 6.7](https://developer.woocommerce.com/2024/11/11/developer-advisory-translation-loading-changes-in-wordpress-6-7/)

![Image](https://github.com/user-attachments/assets/52c03e96-1f4e-40f5-a9e6-2f3507369e82)

### **Steps to Test Extensions Compatibility with Translation Changes**

1. Install WordPress 6.7.1, WooCommerce, and the WooCommerce extension(s) in a local environment with SSL enable.
2. Enable [WP Debug](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) mode.
3. Change the site language in **Settings > General > Site Languag**e to a non-English language with available translations.
4. Verify that translations load correctly in the WooCommerce admin settings and back-end areas.
5. Check the front-end functionality of the extension to ensure user-facing strings are translated properly.
6. Check the server and WordPress debug logs for errors related to translation loading.
7. Document any issues, errors, or log warnings in the below comment on this issue.
8. Expected Result: All strings are correctly translated and no errors are found in log or admin area.

Related Discussion- https://fueled10up.slack.com/archives/C01UCQGPBDJ/p1733327894925469

**Comment by Sourabh208** [comment]
QA Status: ✅
-

- Testing Environment - Local
- WordPress: 6.7.1
- Theme active on store: Twenty Twenty-Five
- WooCommerce - Version 9.4.3
- PHP: 8.2.23
- Web Server: nginx/1.26.1
- Browser: Chrome - Version 130
- OS: macOS Sonoma 14.6.1
- Accommodation Bookings Version: 1.3.0 

1. Verify the Notice Function _load_textdomain_just_in_time should not present for Accommodation Bookings Extension  ✅ Not seen for Accommodation bookings. Highlighted issue is for Bookings which is required for Accommodation Bookings. 

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/3ebee9c0-dabf-4a50-b629-f6df46227e03" />

**Comment by ankitguptaindia** [comment]
Thanks for the testing, @Sourabh208. Closing this issue as no further fixes are needed.
