### ISSUE TITLE
Night count cost adjustment

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-accommodation-bookings#62]
#### What I expected

With Bookings it is possible to have a "block count" cost adjustment so I would expect this to be similar with Accommodation Bookings.

#### What happened instead

No such cost adjustment is available

#### Steps to reproduce the issue

---
- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by geeklore** [comment]
Another customer requested this today.

**Comment by jessepearson** [comment]
Another request via forum thread:
https://wordpress.org/support/topic/block-count-range-type-for-accommodation-product/

**Comment by laurendavissmith** [comment]
Moved to the ideas board
