### ISSUE TITLE
Dates with check in/out not showing as partially booked.

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#76]
Issue reported in 469574-zd-woothemes. Days that have a booked check in or check out should show partially booked in some fashion. Additionally, you are not able to start a new booking on a date that currently has a check out booked.

I believe that if a day only has check in or check out available, the note should state this. It would help clarify what's going on. (that's the enhancement part)
#### Steps to reproduce the issue

Create a product with the min number of nights set to 1:
![screen shot on 2016-09-19 at 12-44-30](https://cloud.githubusercontent.com/assets/4634416/18640644/febf67da-7e66-11e6-9573-e438d08a3ddc.png)

And number of available rooms set to 1:
![screen shot on 2016-09-19 at 12-46-04](https://cloud.githubusercontent.com/assets/4634416/18640670/21a08ff4-7e67-11e6-9756-121ca6190d8f.png)

Then create a booking, or two. I created two, one that is one night (9/21-9/22) and one that is two nights (9/28-9/30):
![screen shot on 2016-09-19 at 12-48-01](https://cloud.githubusercontent.com/assets/4634416/18640719/584decea-7e67-11e6-862e-6fdcd9720ea2.png)

The 21st, 22nd, 28th and 30th should show partially booked, but do not. You can end a booking on the 21st and 28th, which is correct. You cannot start a booking on the 22nd or 30th, but should be able to.

![screen capture on 2016-09-19 at 12-50-21](https://cloud.githubusercontent.com/assets/4634416/18640889/273b94a8-7e68-11e6-8458-f4abafe2edba.gif)

---
- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
May be related:
https://github.com/woothemes/woocommerce-bookings/issues/771

**Comment by WillBrubaker** [comment]
similar in ticket: 471707-zd-woothemes

**Comment by kristinaplauche** [comment]
I picked up this ticket again and tested. I'm getting different results.  I set up the product as above and created bookings as above. I'm using latest releases of Bookings & Accommodations
<img width="582" alt="screen shot 2016-09-28 at 3 12 37 pm" src="https://cloud.githubusercontent.com/assets/16582518/18928426/0b44f208-858e-11e6-928c-2855712e6246.png">
 

>The 21st, 22nd, 28th and 30th should show partially booked, but do not

Agree with this.  My dates were October 20th, 21st, 26th, 28th.  They do not show as partially booked. 
<img width="405" alt="screen shot 2016-09-28 at 3 14 47 pm" src="https://cloud.githubusercontent.com/assets/16582518/18928491/567e65a6-858e-11e6-9759-c600df0174ec.png">


>You cannot start a booking on the 22nd or 30th, but should be able to.

I can start a booking on the 21st (my equivalent of Jesse's 22nd) and the 28th (Jesse's 30th).  See screencast:

![screenshot](http://cld.wthms.co/14FT9/2awNQrS3+)
http://cld.wthms.co/14FT9/2awNQrS3

It's strange that it works for me, but not for @jessepearson and not for the user.

**Comment by kristinaplauche** [comment]
Summarizing the problem(s).

* Partially booked days do not show as partially booked.

* The date that one customer checks out on cannot be used as the same date a different customer checks in on.  **Note:** Changing the checkout time to 00:00 on the checkout date allows the date to be used as a check in date as well.

**Comment by phpmypython** [comment]
So i have done some substantial digging into this and what I have found is that when you click a date in the date picker and it fires to admin_ajax it will eventually call to `get_posted_data` inside of the file `class-wc-booking-form.php` and inside of this method on line `471` you can see the conditional that checks for the `night` booking duration. However the call to `strtotime()` inside of here does not pull in the time that is set in the accommodations plugin it only selects midnight. It looks like this 

```php
else if ( 'night' === $this->product->get_duration_unit() ) {
			$data['_start_date'] = strtotime( "{$data['_year']}-{$data['_month']}-{$data['_day']}" );
			$data['_end_date']   = strtotime( "+{$total_duration} day", $data['_start_date'] );
			$data['_all_day']    = 0;
		}
```

if i instead do this 
```php
else if ( 'night' === $this->product->get_duration_unit() ) {
			$data['_start_date'] = strtotime( "{$data['_year']}-{$data['_month']}-{$data['_day']} 2:00PM" );
			$data['_end_date']   = strtotime( "+{$total_duration} day", $data['_start_date'] );
			$data['_all_day']    = 0;
		}
```
just as test since our check in time is 2PM then all of a sudden it starts working and we can book on check out days. 

So my thinking is that the accommodation plugin needs to hook into a method fired in the ajax call and set the times for the data.

**Comment by kristinaplauche** [comment]
@roykho Bumping this. :) Any word?  Does the above answer help? The customer really needs this working. Thank you!!!

**Comment by roykho** [comment]
We're looking into this next week.

**Comment by larsmagnusherland** [comment]
@roykho any news? Still an issue in our end.

**Comment by dwainm** [comment]
@jessepearson in the latest (bookings core) master: if you supply chekin and checkout times it will ensure that a users bookings can start on a day that another booking ends.

In example below. 2-7 is an existing booking but you can book 1-2. Also see 28-30 is booked, but you can start a boooking from 30 onwards or up to 28. 
<img width="464" alt="screen shot 2016-10-31 at 3 24 30 pm" src="https://cloud.githubusercontent.com/assets/1713474/19855655/6253a18e-9f7e-11e6-8fa0-6707638e1060.png">

The issue of the partial flag showing on accomodation booking is not something we need, because with accomodation we shouldn't see a day as partialy booked. If checkin/checkout is supplied and some booke untill the 30th, the 30th should be available for some one to sart booking from and not show partial booking.

**Comment by dwainm** [comment]
@jessepearson please test and confirm this in the latest masters and close the issue if it is fixed :)

**Comment by larsmagnusherland** [comment]
Verified working in the latest master.

**Comment by dwainm** [comment]
@larsmagnusherland you will also need the latest master of WooCommerce Bookings which is not publically available yet.

**Comment by jessepearson** [comment]
@larsmagnusherland If you create a ticket under the account you purchased Bookings through, then add the ticket number here, I will get you the latest master of Bookings to test with.

**Comment by dwainm** [comment]
@jessepearson could you take a look and confirm this? We'd like to get 1.9.13 along with the next accommodation bookings released.

**Comment by jessepearson** [comment]
@dwainm Looks like the issue still exists. 

I created this booking:
![screen shot on 2016-11-07 at 11 3a24 3a22](https://cloud.githubusercontent.com/assets/4634416/20065636/d77f800a-a4dc-11e6-9249-b370b36f63b6.png)

This is the calendar afterwards:
![screen capture on 2016-11-07 at 11-26-45](https://cloud.githubusercontent.com/assets/4634416/20065731/27cfefb8-a4dd-11e6-9f52-2388c5c3a75b.gif)

The 21st and 23rd should have the triangles to show they are partially booked. For some reason the 21st is the same color as the days in the next month.

**Comment by jessepearson** [comment]
@dwainm Check out dates are still not showing partially booked:

![screen shot 2016-11-08 at 08 46 24](https://cloud.githubusercontent.com/assets/4634416/20101798/7f4697e2-a591-11e6-97aa-3af196626999.png)

On top of that, I noticed that if two bookings are made next to each other and share the first's check out date with the next's check in date, the block is not shown as fully booked.

![screen capture on 2016-11-08 at 08-55-23](https://cloud.githubusercontent.com/assets/4634416/20101886/df669352-a591-11e6-8569-cb961fa4f6af.gif)

In the above example I am using the same product created in the initial report at the top.

**Comment by dwainm** [comment]
@jessepearson what if you purchase those items?

**Comment by jessepearson** [comment]
After order is placed, with order status Pending and booking status Unpaid, the calendar shows no change. After order is Complete/Processing and booking status changed to Paid, the calendar shows partially booked the same as shown above.

**Comment by larsmagnusherland** [comment]
I have the same issue, but in my case it shows as fully available (green) and not partial.

![selection_685](https://cloud.githubusercontent.com/assets/16826379/20109285/b39e73ea-a5df-11e6-9744-a2cb62e8b2f4.png)
![selection_684](https://cloud.githubusercontent.com/assets/16826379/20109286/b39fba02-a5df-11e6-8243-962c7a99bfd7.png)

This is a booked date already, so should be unavailable.

**Comment by larsmagnusherland** [comment]
Issue still exists in 1.0.7
**Example:**
Booking done 3rd of march from 14:00 to 4th of march 11:00 and then 4th of march from 14:00 to 5th of march 11:00 then it shows all green (available) from 3rd to 5th.

![image](https://cloud.githubusercontent.com/assets/16826379/23143027/6285f9f6-f7bf-11e6-8087-a56251b7fec5.png)
![image](https://cloud.githubusercontent.com/assets/16826379/23143079/ad2aba00-f7bf-11e6-9d4c-4bc38f400e12.png)

**Comment by jessepearson** [comment]
@larsmagnusherland We are currently working on the next release of Bookings. It is currently in the beta testing phase. Once it is ready for release, we will get Accommodations compatible with it and push a new release, as well.

**Comment by larsmagnusherland** [comment]
When will this be available? And do you need help in testing?
Currently we have a semi broken page due to this not fully working.

**Comment by mobotter** [comment]
Hi, I'm also waiting for a fix or update for this bug. Hope it will be released soon...

**Comment by jessepearson** [comment]
The new version of Bookings is scheduled to be released in the next few weeks, there is not an exact date as of yet. A new version of Accommodations should follow along with it.

**Comment by bor0** [comment]
I'm wondering why should this be the case, when we have number of available rooms set to 1?

> should show partially booked

In my testings with latest master of Accommodation Bookings and Bookings 1.10.0, it shows as fully booked, which I believe is correct?
![screen shot 2017-04-06 at 10 29 31 am](https://cloud.githubusercontent.com/assets/1620929/24744923/f830e4fe-1ab3-11e7-9512-ddc8df35543e.png)

**Comment by jessepearson** [comment]
@bor0 This is not correct. Since Accomm bookings are overnight, days should only show fully booked if both connecting nights are booked. 

If there is a booking from 26 to 27, both should show partially booked. If the booking is 26 to 28, then 26 and 28 should be partial and 27 should be full. This is the case if the quantity is 1. 

I cannot currently test due to #102

**Comment by linkhousemedia** [comment]
Any update here, folks? This is critical to those using this to make money. Booking is their bread and butter.

**Comment by jessepearson** [comment]
@linkhousemedia Can you confirm what issue you are currently running into. This issue was opened before the latest updates to WooCommerce, Bookings and Accommodations. As far as I can tell, the main issue at this point is just a discrepancy in how the days should be displayed on the calendar. 

The latest releases of Bookings and Accommodations are working with WooCommerce 3.0, and if you create a ticket, then add it here, I can get you dev copies of Bookings and Accomm in order to test the most recent changes.

**Comment by linkhousemedia** [comment]
@jessepearson The exact issue is that the checkout date should show partially available, even if it's booked later that day.  So if the 21st is already booked in the evening, it should at least allow someone to select it as a checkout date.  Right now it shows fully booked. 

I have a woocommerce ticket already - is that what you mean?

**Comment by linkhousemedia** [comment]
@jessepearson my woocommerce ticket is #561586... please advise ASAP. Right now since I've updated woocommerce, the booking accommodation plugin breaks the website.

**Comment by jessepearson** [comment]
@linkhousemedia Just replied. WC 3.0, Bookings 1.10.0 (or the dev copy I sent), and Accomm 1.0.8 should all work together without any critical issues. Feel free to reply to the ticket with anything else.

**Comment by jessepearson** [comment]
@bor0 Here is a great example passed over by @linkhousemedia in his ticket 561586-zd-woothemes

![](http://cld.wthms.co/7qaJ+)
Image Link: http://cld.wthms.co/7qaJ

I have added two bookings to my cart:

* Check in May 8 for a duration of 2 nights, making check out May 10
* Check in May 12 for a duration of 2 nights, making check out May 14

I should be able to select a booking that has a check in of May 10 and a check out of May 12, but I cannot due to May 12 showing fully booked. 

* Days that should be partial: 8, 10, 12, 14
* Days that should be full: 9, 13

Since May 8 and 12 cannot be selected, this is two days that a store owner could be losing business on just in this situation. 

My above example is a new product, the only settings that were changed were to display calendar by default and a cost of 10 per night.

**Comment by madeincosmos** [comment]
One more user reporting the same problem 561628-zd-woothemes

**Comment by woodsdog** [comment]
HI, I'm having the same problem now, was working last week, WC updated and now every hour around a booking I cannot get another booking Unless I take it manually over the phone. This is a serious issue and I think it should be a priority fix? My Ticket Number in their system is #564301 -  unanswered in over 2 days, i have had zero responses from WC. I'm guessing I'm not the only one. Is there a way to go back to the previous version of WC and see if it works again?

**Comment by jessepearson** [comment]
@woodsdog Responses have been taking longer due to the WooCommerce 3.0 release, so we apologize about that. I just assigned your ticket to myself, once I finish up some testing for the next releases of Bookings and Accommodations, I will start working on it.

**Comment by woodsdog** [comment]
Thanks for the heads up, that's a good reason, but you should get that placed on the front end or something maybe so people are aware? New update worked and installed via FTP for me. Back to Business and I can start advertising again  :)

**Comment by linkhousemedia** [comment]
This fix definitely solved the issue for me!  Thanks, everyone.

**Comment by bor0** [comment]
The fix for this will be adjusted in #109 to handle resources (if used) properly.

**Comment by fabrikgrafik** [comment]
This issue still excists when for example you select range of days (not bookable) in the "availability" tab because disabling these dates in the backend will do this based on days and not based on check-in or check-out times. 

For example I want to limit bookings in november, in the availability tab I choose "range of days not bookable from 3 to 15 november". My client wants to book my accommodation from 1 November until 3 November but he can only select 1 and 2 November. 3 November is disabled the whole day. Since the checkout time for all bookings is 10:30AM, it should actually be available partially.

Any fix for this? Thanks!

**Comment by botea14** [comment]
Hi guys,

I use WooCommerce Bookings and WooCommerce Accommodation Bookings plugins.

If i set my product as Bookable product, it displays calendar and featured image and i can select period and book hotel room.

If i select my product as Accommodation product, it only displays the price and the room title.

2 photos attached with booking product and accomodation product.

![accomodation](https://user-images.githubusercontent.com/37483645/37558765-caddbeae-2a21-11e8-97ec-802d54f78baa.PNG)
![bookable](https://user-images.githubusercontent.com/37483645/37558766-cb1fc470-2a21-11e8-9c8a-ec432c9c4da4.PNG)

Thanks.

**Comment by madeincosmos** [comment]
@botea14 sounds like a JavaScript error triggered somewhere. Please submit a ticket for WooCommerce Bookings at https://woocommerce.com/my-account/create-a-ticket/ so we can check this in details.
