### ISSUE TITLE
Accommodations not displaying WC content when used on multisite

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-accommodation-bookings#83]
#### What I expected

That accommodations would work, I tried both activating for the whole network, and for the indivudual site.

#### What happened instead

Instead, I configured everything correct (triple checked), but not all of the features are displaying on the product page, missing:

* Add to cart
* Amount of days selector
* Calendar:

![http://cld.wthms.co/1WKI/4JFxF2S4](http://cld.wthms.co/1WKI/4JFxF2S4+)

With exactly the same configuration on a simple site:

![http://cld.wthms.co/q3g8/NKA19EDY](http://cld.wthms.co/q3g8/NKA19EDY+)

cc @ValeDeOro @roykho

**Comment by bor0** [comment]
Hi @jobthomas, I wasn't able to reproduce this on latest master with Bookings and Accommodation Bookings. Can you please double-check? Thanks!

![untitled12345](https://cloud.githubusercontent.com/assets/1620929/26046767/d528ac06-3950-11e7-8b7a-2d2ab37710fb.gif)

**Comment by jobthomas** [comment]
@bor0 sorry for the very slow reply. It's working now indeed.
