### ISSUE TITLE
Fatal error when using filter to move calendar to first available booking

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#85]
I am getting fatal errors when trying to view an Accomm product with the current Bookings master as of 2016-01-06

```
[06-Jan-2017 16:49:23 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in .../wp-content/plugins/woocommerce-bookings/includes/class-wc-product-booking.php on line 1091
```

#### Steps to reproduce the issue

1. Load current Bookings master
1. Load current Accomm release
1. Create Accomm product
1. View Accomm product on front end, it will die.

@roykho @dwainm 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dwainm** [comment]
@jessepearson we need to thoroughly test  this before 1.9.16 goes out

**Comment by jessepearson** [comment]
I did a little more digging and found it was due to this snippet that I had created for a user that was still in my theme:

```
/**
 * As of Bookings 1.9.13 the current date will be shown in the calendar for performance reasons. 
 * To return to the previous functionality, a filter was put in place. The below function uses this
 * filter to tell Bookings to show the calendar month when the first block is available. 
 */
function move_bookings_calendar_to_first_available_block( $move ) {
	return false;
}
//add_filter( 'wc_bookings_calendar_default_to_current_date', 'move_bookings_calendar_to_first_available_block' );
```

Once I commented it out, I no longer got the fatal errors. Going to remove the Critical tag, but leave it open as users should be able to use this filter without fatal errors.

**Comment by jessepearson** [comment]
Just tested this, it's fixed. I believe since Accomm no longer checks against minutes, this is why it no longer maxes out memory.
