### ISSUE TITLE
Unable to select number of persons

### ISSUE THREAD

**Issue by mgibbs189** [woocommerce/woocommerce-accommodation-bookings#88]
#### What I expected

When on a Booking detail page, I should be able to select the numbers of people.

#### What happened instead

A `Number of people` box doesn't appear, and when I select a date from the calendar, I see this error: `Persons are required - please enter the number of persons above`

Screenshot: http://d.pr/i/lCq4

#### Steps to reproduce the issue

Screencast of the Accommodation product's settings: http://d.pr/v/ziO0

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mgibbs189** [comment]
@dwainm @mattyza Thanks for confirming the bug.

Any ETA on when this will get addressed? Or perhaps some guidance on which file(s) to look in when helping troubleshoot?

**Comment by dwainm** [comment]
@mgibbs189 we're wrapping up the final beta version 1.10.0 of bookings so I'd say another 2 weeks would be a good estimate. Finding the problem file would require the same effort as fixing it as I'm sure this is a small fix. The changes in bookings core may affect this so I don't want to fix it twice ;)

**Comment by jessepearson** [comment]
@mgibbs189 I believe this is a configuration error over a bug, see this screenshot from your screencast:

![](http://cld.wthms.co/uatU/3n05bpOC+)
Image Link: http://cld.wthms.co/uatU/3n05bpOC

You have **Enable person types** selected, but have no Person Types configured. This results in no persons boxes being displayed on the front end. Person Types are for allowing different types of persons, such as Adults and Children, and allowing a different cost for each type. If you are just looking for a total person count you can uncheck that box. 

If you can confirm that's the issue, then I think we can close this report :)

**Comment by mgibbs189** [comment]
@jessepearson Thanks, will pass this back to the customer to confirm. Thanks for following up!

**Comment by jessepearson** [comment]
@mgibbs189 No problem, sorry I didn't chime in sooner, I had accidentally removed myself from watching this repo, so I didn't get a notification with your first report.

**Comment by bor0** [comment]
Any updates on this one @jessepearson? I believe we can close and reopen if needed.

**Comment by jessepearson** [comment]
@bor0 Sorry for the late reply, still trying to catch up on emails from last week. Since we didn't hear back, I'm guessing everything is good. Closing now.
