### ISSUE TITLE
Unpaid and in-cart bookings are still available in the calendar

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#91]
#### Affected ticket(s)

540248-zd-woothemes

#### What I expected

When someone makes a booking for an accommodation product, but hasn't paid for it yet, these dates should be red in the calendar. This is how regular bookable products work - days with unpaid bookings are not available.

#### What happened instead

For accommodation products, unpaid or in-cart bookings don't affect the calendar at all - the date is still green. Only when I try to make a booking on that date, I can see a note saying "there are 0 places remaining":

![Screenshot](http://cld.wthms.co/KU5X+)
Screenshot: http://cld.wthms.co/KU5X

#### Steps to reproduce the issue

1. Create an accommodation product with calendar always visible / max booking per block = 1.
2. Add a booking to cart.
3. Come back to the product page and see the date still shows as green.
4. Try to make another booking on that date and observe the message 'There are 0 places available'.
5. Proceed to checkout and confirm the booking with an offline payment method (check payments etc)
6. Repeat steps 3. & 4.

Problem found in Accommodations 1.0.7 & Bookings 1.9.12. Can't test it with 1.10.beta, because of #90 

-------------------

- [x] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment]
@jessepearson any ideas what we can do here?

**Comment by jessepearson** [comment]
@madeincosmos This should be fixed by [this PR](https://github.com/woocommerce/woocommerce-bookings/pull/942), but it isn't in any versions except the 1.10 Alpha Alpha and Beta releases yet :(

**Comment by bor0** [comment]
This seems to be working fine on latest master of Accommodation and 1.10.0 Bookings:
![screen shot 2017-04-06 at 10 18 38 am](https://cloud.githubusercontent.com/assets/1620929/24744503/8e76f914-1ab2-11e7-8fd5-685eaab98609.png)

@jessepearson / @madeincosmos can you please verify?

**Comment by jessepearson** [comment]
This is fixed with Bookings 1.10.0 and Accomm 1.0.8.
